version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8080"
    environment:
      - KV_VIPER_FILE=./config.yaml
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
    networks:
      - app-network
    command: ["./main", "run", "service"]

  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5555:5432"
    networks:
      - app-network

  redis:
    image: redis:7
    restart: always
    ports:
      - "6381:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
