/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the RegistertionInitiatePost201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegistertionInitiatePost201Response{}

// RegistertionInitiatePost201Response struct for RegistertionInitiatePost201Response
type RegistertionInitiatePost201Response struct {
	Status *float32 `json:"status,omitempty"`
}

// NewRegistertionInitiatePost201Response instantiates a new RegistertionInitiatePost201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegistertionInitiatePost201Response() *RegistertionInitiatePost201Response {
	this := RegistertionInitiatePost201Response{}
	return &this
}

// NewRegistertionInitiatePost201ResponseWithDefaults instantiates a new RegistertionInitiatePost201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegistertionInitiatePost201ResponseWithDefaults() *RegistertionInitiatePost201Response {
	this := RegistertionInitiatePost201Response{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *RegistertionInitiatePost201Response) GetStatus() float32 {
	if o == nil || IsNil(o.Status) {
		var ret float32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistertionInitiatePost201Response) GetStatusOk() (*float32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *RegistertionInitiatePost201Response) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given float32 and assigns it to the Status field.
func (o *RegistertionInitiatePost201Response) SetStatus(v float32) {
	o.Status = &v
}

func (o RegistertionInitiatePost201Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegistertionInitiatePost201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableRegistertionInitiatePost201Response struct {
	value *RegistertionInitiatePost201Response
	isSet bool
}

func (v NullableRegistertionInitiatePost201Response) Get() *RegistertionInitiatePost201Response {
	return v.value
}

func (v *NullableRegistertionInitiatePost201Response) Set(val *RegistertionInitiatePost201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableRegistertionInitiatePost201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableRegistertionInitiatePost201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegistertionInitiatePost201Response(val *RegistertionInitiatePost201Response) *NullableRegistertionInitiatePost201Response {
	return &NullableRegistertionInitiatePost201Response{value: val, isSet: true}
}

func (v NullableRegistertionInitiatePost201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegistertionInitiatePost201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


