/*
Example API

This is a sample API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// LoginReqData - struct for LoginReqData
type LoginReqData struct {
	MapmapOfStringAny *map[string]interface{}
}

// map[string]interface{}AsLoginReqData is a convenience function that returns map[string]interface{} wrapped in LoginReqData
func MapmapOfStringAnyAsLoginReqData(v *map[string]interface{}) LoginReqData {
	return LoginReqData{
		MapmapOfStringAny: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *LoginReqData) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into MapmapOfStringAny
	err = newStrictDecoder(data).Decode(&dst.MapmapOfStringAny)
	if err == nil {
		jsonMapmapOfStringAny, _ := json.Marshal(dst.MapmapOfStringAny)
		if string(jsonMapmapOfStringAny) == "{}" { // empty struct
			dst.MapmapOfStringAny = nil
		} else {
			if err = validator.Validate(dst.MapmapOfStringAny); err != nil {
				dst.MapmapOfStringAny = nil
			} else {
				match++
			}
		}
	} else {
		dst.MapmapOfStringAny = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.MapmapOfStringAny = nil

		return fmt.Errorf("data matches more than one schema in oneOf(LoginReqData)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(LoginReqData)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src LoginReqData) MarshalJSON() ([]byte, error) {
	if src.MapmapOfStringAny != nil {
		return json.Marshal(&src.MapmapOfStringAny)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *LoginReqData) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.MapmapOfStringAny != nil {
		return obj.MapmapOfStringAny
	}

	// all schemas are nil
	return nil
}

type NullableLoginReqData struct {
	value *LoginReqData
	isSet bool
}

func (v NullableLoginReqData) Get() *LoginReqData {
	return v.value
}

func (v *NullableLoginReqData) Set(val *LoginReqData) {
	v.value = val
	v.isSet = true
}

func (v NullableLoginReqData) IsSet() bool {
	return v.isSet
}

func (v *NullableLoginReqData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoginReqData(val *LoginReqData) *NullableLoginReqData {
	return &NullableLoginReqData{value: val, isSet: true}
}

func (v NullableLoginReqData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoginReqData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


