/*
Example API

This is a sample API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LoginReqData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LoginReqData{}

// LoginReqData struct for LoginReqData
type LoginReqData struct {
	Type string `json:"type"`
	Attributes LoginReqDataAttributes `json:"attributes"`
}

type _LoginReqData LoginReqData

// NewLoginReqData instantiates a new LoginReqData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoginReqData(type_ string, attributes LoginReqDataAttributes) *LoginReqData {
	this := LoginReqData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewLoginReqDataWithDefaults instantiates a new LoginReqData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoginReqDataWithDefaults() *LoginReqData {
	this := LoginReqData{}
	return &this
}

// GetType returns the Type field value
func (o *LoginReqData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *LoginReqData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *LoginReqData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *LoginReqData) GetAttributes() LoginReqDataAttributes {
	if o == nil {
		var ret LoginReqDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *LoginReqData) GetAttributesOk() (*LoginReqDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *LoginReqData) SetAttributes(v LoginReqDataAttributes) {
	o.Attributes = v
}

func (o LoginReqData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LoginReqData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *LoginReqData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLoginReqData := _LoginReqData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLoginReqData)

	if err != nil {
		return err
	}

	*o = LoginReqData(varLoginReqData)

	return err
}

type NullableLoginReqData struct {
	value *LoginReqData
	isSet bool
}

func (v NullableLoginReqData) Get() *LoginReqData {
	return v.value
}

func (v *NullableLoginReqData) Set(val *LoginReqData) {
	v.value = val
	v.isSet = true
}

func (v NullableLoginReqData) IsSet() bool {
	return v.isSet
}

func (v *NullableLoginReqData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoginReqData(val *LoginReqData) *NullableLoginReqData {
	return &NullableLoginReqData{value: val, isSet: true}
}

func (v NullableLoginReqData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoginReqData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


