/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OperationDataData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OperationDataData{}

// OperationDataData struct for OperationDataData
type OperationDataData struct {
	Type string `json:"type"`
	Attributes OperationDataDataAttributes `json:"attributes"`
}

type _OperationDataData OperationDataData

// NewOperationDataData instantiates a new OperationDataData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOperationDataData(type_ string, attributes OperationDataDataAttributes) *OperationDataData {
	this := OperationDataData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewOperationDataDataWithDefaults instantiates a new OperationDataData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOperationDataDataWithDefaults() *OperationDataData {
	this := OperationDataData{}
	return &this
}

// GetType returns the Type field value
func (o *OperationDataData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *OperationDataData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *OperationDataData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *OperationDataData) GetAttributes() OperationDataDataAttributes {
	if o == nil {
		var ret OperationDataDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *OperationDataData) GetAttributesOk() (*OperationDataDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *OperationDataData) SetAttributes(v OperationDataDataAttributes) {
	o.Attributes = v
}

func (o OperationDataData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OperationDataData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *OperationDataData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOperationDataData := _OperationDataData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOperationDataData)

	if err != nil {
		return err
	}

	*o = OperationDataData(varOperationDataData)

	return err
}

type NullableOperationDataData struct {
	value *OperationDataData
	isSet bool
}

func (v NullableOperationDataData) Get() *OperationDataData {
	return v.value
}

func (v *NullableOperationDataData) Set(val *OperationDataData) {
	v.value = val
	v.isSet = true
}

func (v NullableOperationDataData) IsSet() bool {
	return v.isSet
}

func (v *NullableOperationDataData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperationDataData(val *OperationDataData) *NullableOperationDataData {
	return &NullableOperationDataData{value: val, isSet: true}
}

func (v NullableOperationDataData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperationDataData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


