/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TokenPairData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenPairData{}

// TokenPairData struct for TokenPairData
type TokenPairData struct {
	Type string `json:"type"`
	Attributes TokenPairDataAttributes `json:"attributes"`
}

type _TokenPairData TokenPairData

// NewTokenPairData instantiates a new TokenPairData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenPairData(type_ string, attributes TokenPairDataAttributes) *TokenPairData {
	this := TokenPairData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewTokenPairDataWithDefaults instantiates a new TokenPairData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenPairDataWithDefaults() *TokenPairData {
	this := TokenPairData{}
	return &this
}

// GetType returns the Type field value
func (o *TokenPairData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TokenPairData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TokenPairData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *TokenPairData) GetAttributes() TokenPairDataAttributes {
	if o == nil {
		var ret TokenPairDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *TokenPairData) GetAttributesOk() (*TokenPairDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *TokenPairData) SetAttributes(v TokenPairDataAttributes) {
	o.Attributes = v
}

func (o TokenPairData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenPairData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *TokenPairData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTokenPairData := _TokenPairData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTokenPairData)

	if err != nil {
		return err
	}

	*o = TokenPairData(varTokenPairData)

	return err
}

type NullableTokenPairData struct {
	value *TokenPairData
	isSet bool
}

func (v NullableTokenPairData) Get() *TokenPairData {
	return v.value
}

func (v *NullableTokenPairData) Set(val *TokenPairData) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenPairData) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenPairData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenPairData(val *TokenPairData) *NullableTokenPairData {
	return &NullableTokenPairData{value: val, isSet: true}
}

func (v NullableTokenPairData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenPairData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


