/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApproveOperation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApproveOperation{}

// ApproveOperation struct for ApproveOperation
type ApproveOperation struct {
	Data ApproveOperationData `json:"data"`
}

type _ApproveOperation ApproveOperation

// NewApproveOperation instantiates a new ApproveOperation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApproveOperation(data ApproveOperationData) *ApproveOperation {
	this := ApproveOperation{}
	this.Data = data
	return &this
}

// NewApproveOperationWithDefaults instantiates a new ApproveOperation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApproveOperationWithDefaults() *ApproveOperation {
	this := ApproveOperation{}
	return &this
}

// GetData returns the Data field value
func (o *ApproveOperation) GetData() ApproveOperationData {
	if o == nil {
		var ret ApproveOperationData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ApproveOperation) GetDataOk() (*ApproveOperationData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ApproveOperation) SetData(v ApproveOperationData) {
	o.Data = v
}

func (o ApproveOperation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApproveOperation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ApproveOperation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApproveOperation := _ApproveOperation{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApproveOperation)

	if err != nil {
		return err
	}

	*o = ApproveOperation(varApproveOperation)

	return err
}

type NullableApproveOperation struct {
	value *ApproveOperation
	isSet bool
}

func (v NullableApproveOperation) Get() *ApproveOperation {
	return v.value
}

func (v *NullableApproveOperation) Set(val *ApproveOperation) {
	v.value = val
	v.isSet = true
}

func (v NullableApproveOperation) IsSet() bool {
	return v.isSet
}

func (v *NullableApproveOperation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApproveOperation(val *ApproveOperation) *NullableApproveOperation {
	return &NullableApproveOperation{value: val, isSet: true}
}

func (v NullableApproveOperation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApproveOperation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


