/*
Example API

This is a sample API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ChangeUsernameReqData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChangeUsernameReqData{}

// ChangeUsernameReqData struct for ChangeUsernameReqData
type ChangeUsernameReqData struct {
	Type string `json:"type"`
	Attributes ChangeUsernameReqDataAttributes `json:"attributes"`
}

type _ChangeUsernameReqData ChangeUsernameReqData

// NewChangeUsernameReqData instantiates a new ChangeUsernameReqData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChangeUsernameReqData(type_ string, attributes ChangeUsernameReqDataAttributes) *ChangeUsernameReqData {
	this := ChangeUsernameReqData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewChangeUsernameReqDataWithDefaults instantiates a new ChangeUsernameReqData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChangeUsernameReqDataWithDefaults() *ChangeUsernameReqData {
	this := ChangeUsernameReqData{}
	return &this
}

// GetType returns the Type field value
func (o *ChangeUsernameReqData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ChangeUsernameReqData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ChangeUsernameReqData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *ChangeUsernameReqData) GetAttributes() ChangeUsernameReqDataAttributes {
	if o == nil {
		var ret ChangeUsernameReqDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *ChangeUsernameReqData) GetAttributesOk() (*ChangeUsernameReqDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *ChangeUsernameReqData) SetAttributes(v ChangeUsernameReqDataAttributes) {
	o.Attributes = v
}

func (o ChangeUsernameReqData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChangeUsernameReqData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *ChangeUsernameReqData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChangeUsernameReqData := _ChangeUsernameReqData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varChangeUsernameReqData)

	if err != nil {
		return err
	}

	*o = ChangeUsernameReqData(varChangeUsernameReqData)

	return err
}

type NullableChangeUsernameReqData struct {
	value *ChangeUsernameReqData
	isSet bool
}

func (v NullableChangeUsernameReqData) Get() *ChangeUsernameReqData {
	return v.value
}

func (v *NullableChangeUsernameReqData) Set(val *ChangeUsernameReqData) {
	v.value = val
	v.isSet = true
}

func (v NullableChangeUsernameReqData) IsSet() bool {
	return v.isSet
}

func (v *NullableChangeUsernameReqData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChangeUsernameReqData(val *ChangeUsernameReqData) *NullableChangeUsernameReqData {
	return &NullableChangeUsernameReqData{value: val, isSet: true}
}

func (v NullableChangeUsernameReqData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChangeUsernameReqData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


