/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApproveOperationReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApproveOperationReq{}

// ApproveOperationReq struct for ApproveOperationReq
type ApproveOperationReq struct {
	Data ApproveOperationReqData `json:"data"`
}

type _ApproveOperationReq ApproveOperationReq

// NewApproveOperationReq instantiates a new ApproveOperationReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApproveOperationReq(data ApproveOperationReqData) *ApproveOperationReq {
	this := ApproveOperationReq{}
	this.Data = data
	return &this
}

// NewApproveOperationReqWithDefaults instantiates a new ApproveOperationReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApproveOperationReqWithDefaults() *ApproveOperationReq {
	this := ApproveOperationReq{}
	return &this
}

// GetData returns the Data field value
func (o *ApproveOperationReq) GetData() ApproveOperationReqData {
	if o == nil {
		var ret ApproveOperationReqData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ApproveOperationReq) GetDataOk() (*ApproveOperationReqData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ApproveOperationReq) SetData(v ApproveOperationReqData) {
	o.Data = v
}

func (o ApproveOperationReq) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApproveOperationReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ApproveOperationReq) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApproveOperationReq := _ApproveOperationReq{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApproveOperationReq)

	if err != nil {
		return err
	}

	*o = ApproveOperationReq(varApproveOperationReq)

	return err
}

type NullableApproveOperationReq struct {
	value *ApproveOperationReq
	isSet bool
}

func (v NullableApproveOperationReq) Get() *ApproveOperationReq {
	return v.value
}

func (v *NullableApproveOperationReq) Set(val *ApproveOperationReq) {
	v.value = val
	v.isSet = true
}

func (v NullableApproveOperationReq) IsSet() bool {
	return v.isSet
}

func (v *NullableApproveOperationReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApproveOperationReq(val *ApproveOperationReq) *NullableApproveOperationReq {
	return &NullableApproveOperationReq{value: val, isSet: true}
}

func (v NullableApproveOperationReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApproveOperationReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


