/*
Example API

This is a sample API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApproveOperationReqData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApproveOperationReqData{}

// ApproveOperationReqData struct for ApproveOperationReqData
type ApproveOperationReqData struct {
	Type string `json:"type"`
	Attributes ApproveOperationReqDataAttributes `json:"attributes"`
}

type _ApproveOperationReqData ApproveOperationReqData

// NewApproveOperationReqData instantiates a new ApproveOperationReqData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApproveOperationReqData(type_ string, attributes ApproveOperationReqDataAttributes) *ApproveOperationReqData {
	this := ApproveOperationReqData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewApproveOperationReqDataWithDefaults instantiates a new ApproveOperationReqData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApproveOperationReqDataWithDefaults() *ApproveOperationReqData {
	this := ApproveOperationReqData{}
	return &this
}

// GetType returns the Type field value
func (o *ApproveOperationReqData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ApproveOperationReqData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ApproveOperationReqData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *ApproveOperationReqData) GetAttributes() ApproveOperationReqDataAttributes {
	if o == nil {
		var ret ApproveOperationReqDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *ApproveOperationReqData) GetAttributesOk() (*ApproveOperationReqDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *ApproveOperationReqData) SetAttributes(v ApproveOperationReqDataAttributes) {
	o.Attributes = v
}

func (o ApproveOperationReqData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApproveOperationReqData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *ApproveOperationReqData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApproveOperationReqData := _ApproveOperationReqData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApproveOperationReqData)

	if err != nil {
		return err
	}

	*o = ApproveOperationReqData(varApproveOperationReqData)

	return err
}

type NullableApproveOperationReqData struct {
	value *ApproveOperationReqData
	isSet bool
}

func (v NullableApproveOperationReqData) Get() *ApproveOperationReqData {
	return v.value
}

func (v *NullableApproveOperationReqData) Set(val *ApproveOperationReqData) {
	v.value = val
	v.isSet = true
}

func (v NullableApproveOperationReqData) IsSet() bool {
	return v.isSet
}

func (v *NullableApproveOperationReqData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApproveOperationReqData(val *ApproveOperationReqData) *NullableApproveOperationReqData {
	return &NullableApproveOperationReqData{value: val, isSet: true}
}

func (v NullableApproveOperationReqData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApproveOperationReqData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


