/*
Example API

This is a sample API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RegistrationReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegistrationReq{}

// RegistrationReq struct for RegistrationReq
type RegistrationReq struct {
	Data RegistrationReqData `json:"data"`
}

type _RegistrationReq RegistrationReq

// NewRegistrationReq instantiates a new RegistrationReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegistrationReq(data RegistrationReqData) *RegistrationReq {
	this := RegistrationReq{}
	this.Data = data
	return &this
}

// NewRegistrationReqWithDefaults instantiates a new RegistrationReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegistrationReqWithDefaults() *RegistrationReq {
	this := RegistrationReq{}
	return &this
}

// GetData returns the Data field value
func (o *RegistrationReq) GetData() RegistrationReqData {
	if o == nil {
		var ret RegistrationReqData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *RegistrationReq) GetDataOk() (*RegistrationReqData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *RegistrationReq) SetData(v RegistrationReqData) {
	o.Data = v
}

func (o RegistrationReq) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegistrationReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *RegistrationReq) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegistrationReq := _RegistrationReq{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegistrationReq)

	if err != nil {
		return err
	}

	*o = RegistrationReq(varRegistrationReq)

	return err
}

type NullableRegistrationReq struct {
	value *RegistrationReq
	isSet bool
}

func (v NullableRegistrationReq) Get() *RegistrationReq {
	return v.value
}

func (v *NullableRegistrationReq) Set(val *RegistrationReq) {
	v.value = val
	v.isSet = true
}

func (v NullableRegistrationReq) IsSet() bool {
	return v.isSet
}

func (v *NullableRegistrationReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegistrationReq(val *RegistrationReq) *NullableRegistrationReq {
	return &NullableRegistrationReq{value: val, isSet: true}
}

func (v NullableRegistrationReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegistrationReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


