/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SessionDataData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SessionDataData{}

// SessionDataData struct for SessionDataData
type SessionDataData struct {
	Type string `json:"type"`
	Attributes SessionDataDataAttributes `json:"attributes"`
}

type _SessionDataData SessionDataData

// NewSessionDataData instantiates a new SessionDataData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSessionDataData(type_ string, attributes SessionDataDataAttributes) *SessionDataData {
	this := SessionDataData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewSessionDataDataWithDefaults instantiates a new SessionDataData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSessionDataDataWithDefaults() *SessionDataData {
	this := SessionDataData{}
	return &this
}

// GetType returns the Type field value
func (o *SessionDataData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SessionDataData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SessionDataData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *SessionDataData) GetAttributes() SessionDataDataAttributes {
	if o == nil {
		var ret SessionDataDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *SessionDataData) GetAttributesOk() (*SessionDataDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *SessionDataData) SetAttributes(v SessionDataDataAttributes) {
	o.Attributes = v
}

func (o SessionDataData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SessionDataData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *SessionDataData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSessionDataData := _SessionDataData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSessionDataData)

	if err != nil {
		return err
	}

	*o = SessionDataData(varSessionDataData)

	return err
}

type NullableSessionDataData struct {
	value *SessionDataData
	isSet bool
}

func (v NullableSessionDataData) Get() *SessionDataData {
	return v.value
}

func (v *NullableSessionDataData) Set(val *SessionDataData) {
	v.value = val
	v.isSet = true
}

func (v NullableSessionDataData) IsSet() bool {
	return v.isSet
}

func (v *NullableSessionDataData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSessionDataData(val *SessionDataData) *NullableSessionDataData {
	return &NullableSessionDataData{value: val, isSet: true}
}

func (v NullableSessionDataData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSessionDataData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


