/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CredentialsData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CredentialsData{}

// CredentialsData struct for CredentialsData
type CredentialsData struct {
	Type string `json:"type"`
	Attributes CredentialsDataAttributes `json:"attributes"`
}

type _CredentialsData CredentialsData

// NewCredentialsData instantiates a new CredentialsData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCredentialsData(type_ string, attributes CredentialsDataAttributes) *CredentialsData {
	this := CredentialsData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewCredentialsDataWithDefaults instantiates a new CredentialsData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCredentialsDataWithDefaults() *CredentialsData {
	this := CredentialsData{}
	return &this
}

// GetType returns the Type field value
func (o *CredentialsData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CredentialsData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CredentialsData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *CredentialsData) GetAttributes() CredentialsDataAttributes {
	if o == nil {
		var ret CredentialsDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *CredentialsData) GetAttributesOk() (*CredentialsDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *CredentialsData) SetAttributes(v CredentialsDataAttributes) {
	o.Attributes = v
}

func (o CredentialsData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CredentialsData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *CredentialsData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCredentialsData := _CredentialsData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCredentialsData)

	if err != nil {
		return err
	}

	*o = CredentialsData(varCredentialsData)

	return err
}

type NullableCredentialsData struct {
	value *CredentialsData
	isSet bool
}

func (v NullableCredentialsData) Get() *CredentialsData {
	return v.value
}

func (v *NullableCredentialsData) Set(val *CredentialsData) {
	v.value = val
	v.isSet = true
}

func (v NullableCredentialsData) IsSet() bool {
	return v.isSet
}

func (v *NullableCredentialsData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCredentialsData(val *CredentialsData) *NullableCredentialsData {
	return &NullableCredentialsData{value: val, isSet: true}
}

func (v NullableCredentialsData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCredentialsData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


