/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ResetPasswordCompleteData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResetPasswordCompleteData{}

// ResetPasswordCompleteData struct for ResetPasswordCompleteData
type ResetPasswordCompleteData struct {
	Type string `json:"type"`
	Attributes ResetPasswordCompleteDataAttributes `json:"attributes"`
}

type _ResetPasswordCompleteData ResetPasswordCompleteData

// NewResetPasswordCompleteData instantiates a new ResetPasswordCompleteData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResetPasswordCompleteData(type_ string, attributes ResetPasswordCompleteDataAttributes) *ResetPasswordCompleteData {
	this := ResetPasswordCompleteData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewResetPasswordCompleteDataWithDefaults instantiates a new ResetPasswordCompleteData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResetPasswordCompleteDataWithDefaults() *ResetPasswordCompleteData {
	this := ResetPasswordCompleteData{}
	return &this
}

// GetType returns the Type field value
func (o *ResetPasswordCompleteData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ResetPasswordCompleteData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ResetPasswordCompleteData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *ResetPasswordCompleteData) GetAttributes() ResetPasswordCompleteDataAttributes {
	if o == nil {
		var ret ResetPasswordCompleteDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *ResetPasswordCompleteData) GetAttributesOk() (*ResetPasswordCompleteDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *ResetPasswordCompleteData) SetAttributes(v ResetPasswordCompleteDataAttributes) {
	o.Attributes = v
}

func (o ResetPasswordCompleteData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResetPasswordCompleteData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *ResetPasswordCompleteData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResetPasswordCompleteData := _ResetPasswordCompleteData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResetPasswordCompleteData)

	if err != nil {
		return err
	}

	*o = ResetPasswordCompleteData(varResetPasswordCompleteData)

	return err
}

type NullableResetPasswordCompleteData struct {
	value *ResetPasswordCompleteData
	isSet bool
}

func (v NullableResetPasswordCompleteData) Get() *ResetPasswordCompleteData {
	return v.value
}

func (v *NullableResetPasswordCompleteData) Set(val *ResetPasswordCompleteData) {
	v.value = val
	v.isSet = true
}

func (v NullableResetPasswordCompleteData) IsSet() bool {
	return v.isSet
}

func (v *NullableResetPasswordCompleteData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResetPasswordCompleteData(val *ResetPasswordCompleteData) *NullableResetPasswordCompleteData {
	return &NullableResetPasswordCompleteData{value: val, isSet: true}
}

func (v NullableResetPasswordCompleteData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResetPasswordCompleteData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


