/*
Example API

This is a sample API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LoginRespDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LoginRespDataAttributes{}

// LoginRespDataAttributes struct for LoginRespDataAttributes
type LoginRespDataAttributes struct {
	// JWT access token for API access
	AccessToken string `json:"access_token"`
	// JWT refresh token for generating new access tokens
	RefreshToken string `json:"refresh_token"`
	// Type of the token, typically 'Bearer'
	TokenType string `json:"token_type"`
}

type _LoginRespDataAttributes LoginRespDataAttributes

// NewLoginRespDataAttributes instantiates a new LoginRespDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoginRespDataAttributes(accessToken string, refreshToken string, tokenType string) *LoginRespDataAttributes {
	this := LoginRespDataAttributes{}
	this.AccessToken = accessToken
	this.RefreshToken = refreshToken
	this.TokenType = tokenType
	return &this
}

// NewLoginRespDataAttributesWithDefaults instantiates a new LoginRespDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoginRespDataAttributesWithDefaults() *LoginRespDataAttributes {
	this := LoginRespDataAttributes{}
	return &this
}

// GetAccessToken returns the AccessToken field value
func (o *LoginRespDataAttributes) GetAccessToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessToken
}

// GetAccessTokenOk returns a tuple with the AccessToken field value
// and a boolean to check if the value has been set.
func (o *LoginRespDataAttributes) GetAccessTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessToken, true
}

// SetAccessToken sets field value
func (o *LoginRespDataAttributes) SetAccessToken(v string) {
	o.AccessToken = v
}

// GetRefreshToken returns the RefreshToken field value
func (o *LoginRespDataAttributes) GetRefreshToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RefreshToken
}

// GetRefreshTokenOk returns a tuple with the RefreshToken field value
// and a boolean to check if the value has been set.
func (o *LoginRespDataAttributes) GetRefreshTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RefreshToken, true
}

// SetRefreshToken sets field value
func (o *LoginRespDataAttributes) SetRefreshToken(v string) {
	o.RefreshToken = v
}

// GetTokenType returns the TokenType field value
func (o *LoginRespDataAttributes) GetTokenType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenType
}

// GetTokenTypeOk returns a tuple with the TokenType field value
// and a boolean to check if the value has been set.
func (o *LoginRespDataAttributes) GetTokenTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenType, true
}

// SetTokenType sets field value
func (o *LoginRespDataAttributes) SetTokenType(v string) {
	o.TokenType = v
}

func (o LoginRespDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LoginRespDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["access_token"] = o.AccessToken
	toSerialize["refresh_token"] = o.RefreshToken
	toSerialize["token_type"] = o.TokenType
	return toSerialize, nil
}

func (o *LoginRespDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"access_token",
		"refresh_token",
		"token_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLoginRespDataAttributes := _LoginRespDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLoginRespDataAttributes)

	if err != nil {
		return err
	}

	*o = LoginRespDataAttributes(varLoginRespDataAttributes)

	return err
}

type NullableLoginRespDataAttributes struct {
	value *LoginRespDataAttributes
	isSet bool
}

func (v NullableLoginRespDataAttributes) Get() *LoginRespDataAttributes {
	return v.value
}

func (v *NullableLoginRespDataAttributes) Set(val *LoginRespDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableLoginRespDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableLoginRespDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoginRespDataAttributes(val *LoginRespDataAttributes) *NullableLoginRespDataAttributes {
	return &NullableLoginRespDataAttributes{value: val, isSet: true}
}

func (v NullableLoginRespDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoginRespDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


