/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LoginInitiate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LoginInitiate{}

// LoginInitiate struct for LoginInitiate
type LoginInitiate struct {
	Data LoginInitiateData `json:"data"`
}

type _LoginInitiate LoginInitiate

// NewLoginInitiate instantiates a new LoginInitiate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoginInitiate(data LoginInitiateData) *LoginInitiate {
	this := LoginInitiate{}
	this.Data = data
	return &this
}

// NewLoginInitiateWithDefaults instantiates a new LoginInitiate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoginInitiateWithDefaults() *LoginInitiate {
	this := LoginInitiate{}
	return &this
}

// GetData returns the Data field value
func (o *LoginInitiate) GetData() LoginInitiateData {
	if o == nil {
		var ret LoginInitiateData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *LoginInitiate) GetDataOk() (*LoginInitiateData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *LoginInitiate) SetData(v LoginInitiateData) {
	o.Data = v
}

func (o LoginInitiate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LoginInitiate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *LoginInitiate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLoginInitiate := _LoginInitiate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLoginInitiate)

	if err != nil {
		return err
	}

	*o = LoginInitiate(varLoginInitiate)

	return err
}

type NullableLoginInitiate struct {
	value *LoginInitiate
	isSet bool
}

func (v NullableLoginInitiate) Get() *LoginInitiate {
	return v.value
}

func (v *NullableLoginInitiate) Set(val *LoginInitiate) {
	v.value = val
	v.isSet = true
}

func (v NullableLoginInitiate) IsSet() bool {
	return v.isSet
}

func (v *NullableLoginInitiate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoginInitiate(val *LoginInitiate) *NullableLoginInitiate {
	return &NullableLoginInitiate{value: val, isSet: true}
}

func (v NullableLoginInitiate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoginInitiate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


