/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UserSessionsDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserSessionsDataAttributes{}

// UserSessionsDataAttributes struct for UserSessionsDataAttributes
type UserSessionsDataAttributes struct {
	Devices []UserSessionsDataAttributesDevicesInner `json:"devices"`
}

type _UserSessionsDataAttributes UserSessionsDataAttributes

// NewUserSessionsDataAttributes instantiates a new UserSessionsDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserSessionsDataAttributes(devices []UserSessionsDataAttributesDevicesInner) *UserSessionsDataAttributes {
	this := UserSessionsDataAttributes{}
	this.Devices = devices
	return &this
}

// NewUserSessionsDataAttributesWithDefaults instantiates a new UserSessionsDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserSessionsDataAttributesWithDefaults() *UserSessionsDataAttributes {
	this := UserSessionsDataAttributes{}
	return &this
}

// GetDevices returns the Devices field value
func (o *UserSessionsDataAttributes) GetDevices() []UserSessionsDataAttributesDevicesInner {
	if o == nil {
		var ret []UserSessionsDataAttributesDevicesInner
		return ret
	}

	return o.Devices
}

// GetDevicesOk returns a tuple with the Devices field value
// and a boolean to check if the value has been set.
func (o *UserSessionsDataAttributes) GetDevicesOk() ([]UserSessionsDataAttributesDevicesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Devices, true
}

// SetDevices sets field value
func (o *UserSessionsDataAttributes) SetDevices(v []UserSessionsDataAttributesDevicesInner) {
	o.Devices = v
}

func (o UserSessionsDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserSessionsDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["devices"] = o.Devices
	return toSerialize, nil
}

func (o *UserSessionsDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"devices",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserSessionsDataAttributes := _UserSessionsDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserSessionsDataAttributes)

	if err != nil {
		return err
	}

	*o = UserSessionsDataAttributes(varUserSessionsDataAttributes)

	return err
}

type NullableUserSessionsDataAttributes struct {
	value *UserSessionsDataAttributes
	isSet bool
}

func (v NullableUserSessionsDataAttributes) Get() *UserSessionsDataAttributes {
	return v.value
}

func (v *NullableUserSessionsDataAttributes) Set(val *UserSessionsDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUserSessionsDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUserSessionsDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserSessionsDataAttributes(val *UserSessionsDataAttributes) *NullableUserSessionsDataAttributes {
	return &NullableUserSessionsDataAttributes{value: val, isSet: true}
}

func (v NullableUserSessionsDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserSessionsDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


