/*
Example API

This is a sample API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RegistrationReqData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegistrationReqData{}

// RegistrationReqData struct for RegistrationReqData
type RegistrationReqData struct {
	// Unique identifier username
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes RegistrationReqDataAttributes `json:"attributes"`
}

type _RegistrationReqData RegistrationReqData

// NewRegistrationReqData instantiates a new RegistrationReqData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegistrationReqData(id string, type_ string, attributes RegistrationReqDataAttributes) *RegistrationReqData {
	this := RegistrationReqData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewRegistrationReqDataWithDefaults instantiates a new RegistrationReqData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegistrationReqDataWithDefaults() *RegistrationReqData {
	this := RegistrationReqData{}
	return &this
}

// GetId returns the Id field value
func (o *RegistrationReqData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RegistrationReqData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RegistrationReqData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *RegistrationReqData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *RegistrationReqData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *RegistrationReqData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *RegistrationReqData) GetAttributes() RegistrationReqDataAttributes {
	if o == nil {
		var ret RegistrationReqDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *RegistrationReqData) GetAttributesOk() (*RegistrationReqDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *RegistrationReqData) SetAttributes(v RegistrationReqDataAttributes) {
	o.Attributes = v
}

func (o RegistrationReqData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegistrationReqData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *RegistrationReqData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegistrationReqData := _RegistrationReqData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegistrationReqData)

	if err != nil {
		return err
	}

	*o = RegistrationReqData(varRegistrationReqData)

	return err
}

type NullableRegistrationReqData struct {
	value *RegistrationReqData
	isSet bool
}

func (v NullableRegistrationReqData) Get() *RegistrationReqData {
	return v.value
}

func (v *NullableRegistrationReqData) Set(val *RegistrationReqData) {
	v.value = val
	v.isSet = true
}

func (v NullableRegistrationReqData) IsSet() bool {
	return v.isSet
}

func (v *NullableRegistrationReqData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegistrationReqData(val *RegistrationReqData) *NullableRegistrationReqData {
	return &NullableRegistrationReqData{value: val, isSet: true}
}

func (v NullableRegistrationReqData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegistrationReqData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


