/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SessionsDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SessionsDataAttributes{}

// SessionsDataAttributes struct for SessionsDataAttributes
type SessionsDataAttributes struct {
	Devices []SessionsDataAttributesDevicesInner `json:"devices"`
}

type _SessionsDataAttributes SessionsDataAttributes

// NewSessionsDataAttributes instantiates a new SessionsDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSessionsDataAttributes(devices []SessionsDataAttributesDevicesInner) *SessionsDataAttributes {
	this := SessionsDataAttributes{}
	this.Devices = devices
	return &this
}

// NewSessionsDataAttributesWithDefaults instantiates a new SessionsDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSessionsDataAttributesWithDefaults() *SessionsDataAttributes {
	this := SessionsDataAttributes{}
	return &this
}

// GetDevices returns the Devices field value
func (o *SessionsDataAttributes) GetDevices() []SessionsDataAttributesDevicesInner {
	if o == nil {
		var ret []SessionsDataAttributesDevicesInner
		return ret
	}

	return o.Devices
}

// GetDevicesOk returns a tuple with the Devices field value
// and a boolean to check if the value has been set.
func (o *SessionsDataAttributes) GetDevicesOk() ([]SessionsDataAttributesDevicesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Devices, true
}

// SetDevices sets field value
func (o *SessionsDataAttributes) SetDevices(v []SessionsDataAttributesDevicesInner) {
	o.Devices = v
}

func (o SessionsDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SessionsDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["devices"] = o.Devices
	return toSerialize, nil
}

func (o *SessionsDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"devices",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSessionsDataAttributes := _SessionsDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSessionsDataAttributes)

	if err != nil {
		return err
	}

	*o = SessionsDataAttributes(varSessionsDataAttributes)

	return err
}

type NullableSessionsDataAttributes struct {
	value *SessionsDataAttributes
	isSet bool
}

func (v NullableSessionsDataAttributes) Get() *SessionsDataAttributes {
	return v.value
}

func (v *NullableSessionsDataAttributes) Set(val *SessionsDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableSessionsDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableSessionsDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSessionsDataAttributes(val *SessionsDataAttributes) *NullableSessionsDataAttributes {
	return &NullableSessionsDataAttributes{value: val, isSet: true}
}

func (v NullableSessionsDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSessionsDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


