/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RegistrationCompleteDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegistrationCompleteDataAttributes{}

// RegistrationCompleteDataAttributes struct for RegistrationCompleteDataAttributes
type RegistrationCompleteDataAttributes struct {
	// User password
	Password string `json:"password"`
	// User email
	Email string `json:"email"`
}

type _RegistrationCompleteDataAttributes RegistrationCompleteDataAttributes

// NewRegistrationCompleteDataAttributes instantiates a new RegistrationCompleteDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegistrationCompleteDataAttributes(password string, email string) *RegistrationCompleteDataAttributes {
	this := RegistrationCompleteDataAttributes{}
	this.Password = password
	this.Email = email
	return &this
}

// NewRegistrationCompleteDataAttributesWithDefaults instantiates a new RegistrationCompleteDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegistrationCompleteDataAttributesWithDefaults() *RegistrationCompleteDataAttributes {
	this := RegistrationCompleteDataAttributes{}
	return &this
}

// GetPassword returns the Password field value
func (o *RegistrationCompleteDataAttributes) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *RegistrationCompleteDataAttributes) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *RegistrationCompleteDataAttributes) SetPassword(v string) {
	o.Password = v
}

// GetEmail returns the Email field value
func (o *RegistrationCompleteDataAttributes) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *RegistrationCompleteDataAttributes) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *RegistrationCompleteDataAttributes) SetEmail(v string) {
	o.Email = v
}

func (o RegistrationCompleteDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegistrationCompleteDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["password"] = o.Password
	toSerialize["email"] = o.Email
	return toSerialize, nil
}

func (o *RegistrationCompleteDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"password",
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegistrationCompleteDataAttributes := _RegistrationCompleteDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegistrationCompleteDataAttributes)

	if err != nil {
		return err
	}

	*o = RegistrationCompleteDataAttributes(varRegistrationCompleteDataAttributes)

	return err
}

type NullableRegistrationCompleteDataAttributes struct {
	value *RegistrationCompleteDataAttributes
	isSet bool
}

func (v NullableRegistrationCompleteDataAttributes) Get() *RegistrationCompleteDataAttributes {
	return v.value
}

func (v *NullableRegistrationCompleteDataAttributes) Set(val *RegistrationCompleteDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableRegistrationCompleteDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableRegistrationCompleteDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegistrationCompleteDataAttributes(val *RegistrationCompleteDataAttributes) *NullableRegistrationCompleteDataAttributes {
	return &NullableRegistrationCompleteDataAttributes{value: val, isSet: true}
}

func (v NullableRegistrationCompleteDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegistrationCompleteDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


