/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApproveOperationData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApproveOperationData{}

// ApproveOperationData struct for ApproveOperationData
type ApproveOperationData struct {
	Type string `json:"type"`
	Attributes ApproveOperationDataAttributes `json:"attributes"`
}

type _ApproveOperationData ApproveOperationData

// NewApproveOperationData instantiates a new ApproveOperationData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApproveOperationData(type_ string, attributes ApproveOperationDataAttributes) *ApproveOperationData {
	this := ApproveOperationData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewApproveOperationDataWithDefaults instantiates a new ApproveOperationData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApproveOperationDataWithDefaults() *ApproveOperationData {
	this := ApproveOperationData{}
	return &this
}

// GetType returns the Type field value
func (o *ApproveOperationData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ApproveOperationData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ApproveOperationData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *ApproveOperationData) GetAttributes() ApproveOperationDataAttributes {
	if o == nil {
		var ret ApproveOperationDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *ApproveOperationData) GetAttributesOk() (*ApproveOperationDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *ApproveOperationData) SetAttributes(v ApproveOperationDataAttributes) {
	o.Attributes = v
}

func (o ApproveOperationData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApproveOperationData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *ApproveOperationData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApproveOperationData := _ApproveOperationData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApproveOperationData)

	if err != nil {
		return err
	}

	*o = ApproveOperationData(varApproveOperationData)

	return err
}

type NullableApproveOperationData struct {
	value *ApproveOperationData
	isSet bool
}

func (v NullableApproveOperationData) Get() *ApproveOperationData {
	return v.value
}

func (v *NullableApproveOperationData) Set(val *ApproveOperationData) {
	v.value = val
	v.isSet = true
}

func (v NullableApproveOperationData) IsSet() bool {
	return v.isSet
}

func (v *NullableApproveOperationData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApproveOperationData(val *ApproveOperationData) *NullableApproveOperationData {
	return &NullableApproveOperationData{value: val, isSet: true}
}

func (v NullableApproveOperationData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApproveOperationData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


