/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the UserChangeTerminateSessionsDelete200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserChangeTerminateSessionsDelete200Response{}

// UserChangeTerminateSessionsDelete200Response struct for UserChangeTerminateSessionsDelete200Response
type UserChangeTerminateSessionsDelete200Response struct {
	Status *float32 `json:"status,omitempty"`
}

// NewUserChangeTerminateSessionsDelete200Response instantiates a new UserChangeTerminateSessionsDelete200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserChangeTerminateSessionsDelete200Response() *UserChangeTerminateSessionsDelete200Response {
	this := UserChangeTerminateSessionsDelete200Response{}
	return &this
}

// NewUserChangeTerminateSessionsDelete200ResponseWithDefaults instantiates a new UserChangeTerminateSessionsDelete200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserChangeTerminateSessionsDelete200ResponseWithDefaults() *UserChangeTerminateSessionsDelete200Response {
	this := UserChangeTerminateSessionsDelete200Response{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *UserChangeTerminateSessionsDelete200Response) GetStatus() float32 {
	if o == nil || IsNil(o.Status) {
		var ret float32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserChangeTerminateSessionsDelete200Response) GetStatusOk() (*float32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *UserChangeTerminateSessionsDelete200Response) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given float32 and assigns it to the Status field.
func (o *UserChangeTerminateSessionsDelete200Response) SetStatus(v float32) {
	o.Status = &v
}

func (o UserChangeTerminateSessionsDelete200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserChangeTerminateSessionsDelete200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableUserChangeTerminateSessionsDelete200Response struct {
	value *UserChangeTerminateSessionsDelete200Response
	isSet bool
}

func (v NullableUserChangeTerminateSessionsDelete200Response) Get() *UserChangeTerminateSessionsDelete200Response {
	return v.value
}

func (v *NullableUserChangeTerminateSessionsDelete200Response) Set(val *UserChangeTerminateSessionsDelete200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUserChangeTerminateSessionsDelete200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUserChangeTerminateSessionsDelete200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserChangeTerminateSessionsDelete200Response(val *UserChangeTerminateSessionsDelete200Response) *NullableUserChangeTerminateSessionsDelete200Response {
	return &NullableUserChangeTerminateSessionsDelete200Response{value: val, isSet: true}
}

func (v NullableUserChangeTerminateSessionsDelete200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserChangeTerminateSessionsDelete200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


