/*
Example API

This is a sample API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ForgotPasswordReqData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ForgotPasswordReqData{}

// ForgotPasswordReqData struct for ForgotPasswordReqData
type ForgotPasswordReqData struct {
	Type string `json:"type"`
	Attributes ForgotPasswordReqDataAttributes `json:"attributes"`
}

type _ForgotPasswordReqData ForgotPasswordReqData

// NewForgotPasswordReqData instantiates a new ForgotPasswordReqData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewForgotPasswordReqData(type_ string, attributes ForgotPasswordReqDataAttributes) *ForgotPasswordReqData {
	this := ForgotPasswordReqData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewForgotPasswordReqDataWithDefaults instantiates a new ForgotPasswordReqData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewForgotPasswordReqDataWithDefaults() *ForgotPasswordReqData {
	this := ForgotPasswordReqData{}
	return &this
}

// GetType returns the Type field value
func (o *ForgotPasswordReqData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ForgotPasswordReqData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ForgotPasswordReqData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *ForgotPasswordReqData) GetAttributes() ForgotPasswordReqDataAttributes {
	if o == nil {
		var ret ForgotPasswordReqDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *ForgotPasswordReqData) GetAttributesOk() (*ForgotPasswordReqDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *ForgotPasswordReqData) SetAttributes(v ForgotPasswordReqDataAttributes) {
	o.Attributes = v
}

func (o ForgotPasswordReqData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ForgotPasswordReqData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *ForgotPasswordReqData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varForgotPasswordReqData := _ForgotPasswordReqData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varForgotPasswordReqData)

	if err != nil {
		return err
	}

	*o = ForgotPasswordReqData(varForgotPasswordReqData)

	return err
}

type NullableForgotPasswordReqData struct {
	value *ForgotPasswordReqData
	isSet bool
}

func (v NullableForgotPasswordReqData) Get() *ForgotPasswordReqData {
	return v.value
}

func (v *NullableForgotPasswordReqData) Set(val *ForgotPasswordReqData) {
	v.value = val
	v.isSet = true
}

func (v NullableForgotPasswordReqData) IsSet() bool {
	return v.isSet
}

func (v *NullableForgotPasswordReqData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableForgotPasswordReqData(val *ForgotPasswordReqData) *NullableForgotPasswordReqData {
	return &NullableForgotPasswordReqData{value: val, isSet: true}
}

func (v NullableForgotPasswordReqData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableForgotPasswordReqData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


