/*
Example API

This is a sample API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RegistrationCompleteDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegistrationCompleteDataAttributes{}

// RegistrationCompleteDataAttributes struct for RegistrationCompleteDataAttributes
type RegistrationCompleteDataAttributes struct {
	// First password
	FirstPassword string `json:"first_password"`
	// Second password
	SecondPassword string `json:"second_password"`
	// User email
	Email string `json:"email"`
	// User username
	Username *string `json:"username,omitempty"`
}

type _RegistrationCompleteDataAttributes RegistrationCompleteDataAttributes

// NewRegistrationCompleteDataAttributes instantiates a new RegistrationCompleteDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegistrationCompleteDataAttributes(firstPassword string, secondPassword string, email string) *RegistrationCompleteDataAttributes {
	this := RegistrationCompleteDataAttributes{}
	this.FirstPassword = firstPassword
	this.SecondPassword = secondPassword
	this.Email = email
	return &this
}

// NewRegistrationCompleteDataAttributesWithDefaults instantiates a new RegistrationCompleteDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegistrationCompleteDataAttributesWithDefaults() *RegistrationCompleteDataAttributes {
	this := RegistrationCompleteDataAttributes{}
	return &this
}

// GetFirstPassword returns the FirstPassword field value
func (o *RegistrationCompleteDataAttributes) GetFirstPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FirstPassword
}

// GetFirstPasswordOk returns a tuple with the FirstPassword field value
// and a boolean to check if the value has been set.
func (o *RegistrationCompleteDataAttributes) GetFirstPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FirstPassword, true
}

// SetFirstPassword sets field value
func (o *RegistrationCompleteDataAttributes) SetFirstPassword(v string) {
	o.FirstPassword = v
}

// GetSecondPassword returns the SecondPassword field value
func (o *RegistrationCompleteDataAttributes) GetSecondPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SecondPassword
}

// GetSecondPasswordOk returns a tuple with the SecondPassword field value
// and a boolean to check if the value has been set.
func (o *RegistrationCompleteDataAttributes) GetSecondPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SecondPassword, true
}

// SetSecondPassword sets field value
func (o *RegistrationCompleteDataAttributes) SetSecondPassword(v string) {
	o.SecondPassword = v
}

// GetEmail returns the Email field value
func (o *RegistrationCompleteDataAttributes) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *RegistrationCompleteDataAttributes) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *RegistrationCompleteDataAttributes) SetEmail(v string) {
	o.Email = v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *RegistrationCompleteDataAttributes) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistrationCompleteDataAttributes) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *RegistrationCompleteDataAttributes) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *RegistrationCompleteDataAttributes) SetUsername(v string) {
	o.Username = &v
}

func (o RegistrationCompleteDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegistrationCompleteDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["first_password"] = o.FirstPassword
	toSerialize["second_password"] = o.SecondPassword
	toSerialize["email"] = o.Email
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	return toSerialize, nil
}

func (o *RegistrationCompleteDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"first_password",
		"second_password",
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegistrationCompleteDataAttributes := _RegistrationCompleteDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegistrationCompleteDataAttributes)

	if err != nil {
		return err
	}

	*o = RegistrationCompleteDataAttributes(varRegistrationCompleteDataAttributes)

	return err
}

type NullableRegistrationCompleteDataAttributes struct {
	value *RegistrationCompleteDataAttributes
	isSet bool
}

func (v NullableRegistrationCompleteDataAttributes) Get() *RegistrationCompleteDataAttributes {
	return v.value
}

func (v *NullableRegistrationCompleteDataAttributes) Set(val *RegistrationCompleteDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableRegistrationCompleteDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableRegistrationCompleteDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegistrationCompleteDataAttributes(val *RegistrationCompleteDataAttributes) *NullableRegistrationCompleteDataAttributes {
	return &NullableRegistrationCompleteDataAttributes{value: val, isSet: true}
}

func (v NullableRegistrationCompleteDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegistrationCompleteDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


