/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LoginCompleteReqDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LoginCompleteReqDataAttributes{}

// LoginCompleteReqDataAttributes struct for LoginCompleteReqDataAttributes
type LoginCompleteReqDataAttributes struct {
	// User email
	Email string `json:"email"`
	// Device name
	DeviceName string `json:"device_name"`
}

type _LoginCompleteReqDataAttributes LoginCompleteReqDataAttributes

// NewLoginCompleteReqDataAttributes instantiates a new LoginCompleteReqDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoginCompleteReqDataAttributes(email string, deviceName string) *LoginCompleteReqDataAttributes {
	this := LoginCompleteReqDataAttributes{}
	this.Email = email
	this.DeviceName = deviceName
	return &this
}

// NewLoginCompleteReqDataAttributesWithDefaults instantiates a new LoginCompleteReqDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoginCompleteReqDataAttributesWithDefaults() *LoginCompleteReqDataAttributes {
	this := LoginCompleteReqDataAttributes{}
	return &this
}

// GetEmail returns the Email field value
func (o *LoginCompleteReqDataAttributes) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *LoginCompleteReqDataAttributes) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *LoginCompleteReqDataAttributes) SetEmail(v string) {
	o.Email = v
}

// GetDeviceName returns the DeviceName field value
func (o *LoginCompleteReqDataAttributes) GetDeviceName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeviceName
}

// GetDeviceNameOk returns a tuple with the DeviceName field value
// and a boolean to check if the value has been set.
func (o *LoginCompleteReqDataAttributes) GetDeviceNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceName, true
}

// SetDeviceName sets field value
func (o *LoginCompleteReqDataAttributes) SetDeviceName(v string) {
	o.DeviceName = v
}

func (o LoginCompleteReqDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LoginCompleteReqDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	toSerialize["device_name"] = o.DeviceName
	return toSerialize, nil
}

func (o *LoginCompleteReqDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"device_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLoginCompleteReqDataAttributes := _LoginCompleteReqDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLoginCompleteReqDataAttributes)

	if err != nil {
		return err
	}

	*o = LoginCompleteReqDataAttributes(varLoginCompleteReqDataAttributes)

	return err
}

type NullableLoginCompleteReqDataAttributes struct {
	value *LoginCompleteReqDataAttributes
	isSet bool
}

func (v NullableLoginCompleteReqDataAttributes) Get() *LoginCompleteReqDataAttributes {
	return v.value
}

func (v *NullableLoginCompleteReqDataAttributes) Set(val *LoginCompleteReqDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableLoginCompleteReqDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableLoginCompleteReqDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoginCompleteReqDataAttributes(val *LoginCompleteReqDataAttributes) *NullableLoginCompleteReqDataAttributes {
	return &NullableLoginCompleteReqDataAttributes{value: val, isSet: true}
}

func (v NullableLoginCompleteReqDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoginCompleteReqDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


