/*
Example API

This is a sample API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ActivateEmailData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ActivateEmailData{}

// ActivateEmailData struct for ActivateEmailData
type ActivateEmailData struct {
	Type string `json:"type"`
	Attributes ActivateEmailDataAttributes `json:"attributes"`
}

type _ActivateEmailData ActivateEmailData

// NewActivateEmailData instantiates a new ActivateEmailData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActivateEmailData(type_ string, attributes ActivateEmailDataAttributes) *ActivateEmailData {
	this := ActivateEmailData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewActivateEmailDataWithDefaults instantiates a new ActivateEmailData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActivateEmailDataWithDefaults() *ActivateEmailData {
	this := ActivateEmailData{}
	return &this
}

// GetType returns the Type field value
func (o *ActivateEmailData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ActivateEmailData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ActivateEmailData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *ActivateEmailData) GetAttributes() ActivateEmailDataAttributes {
	if o == nil {
		var ret ActivateEmailDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *ActivateEmailData) GetAttributesOk() (*ActivateEmailDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *ActivateEmailData) SetAttributes(v ActivateEmailDataAttributes) {
	o.Attributes = v
}

func (o ActivateEmailData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ActivateEmailData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *ActivateEmailData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varActivateEmailData := _ActivateEmailData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varActivateEmailData)

	if err != nil {
		return err
	}

	*o = ActivateEmailData(varActivateEmailData)

	return err
}

type NullableActivateEmailData struct {
	value *ActivateEmailData
	isSet bool
}

func (v NullableActivateEmailData) Get() *ActivateEmailData {
	return v.value
}

func (v *NullableActivateEmailData) Set(val *ActivateEmailData) {
	v.value = val
	v.isSet = true
}

func (v NullableActivateEmailData) IsSet() bool {
	return v.isSet
}

func (v *NullableActivateEmailData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActivateEmailData(val *ActivateEmailData) *NullableActivateEmailData {
	return &NullableActivateEmailData{value: val, isSet: true}
}

func (v NullableActivateEmailData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActivateEmailData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


