/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EmailDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmailDataAttributes{}

// EmailDataAttributes struct for EmailDataAttributes
type EmailDataAttributes struct {
	// User email
	Email string `json:"email"`
}

type _EmailDataAttributes EmailDataAttributes

// NewEmailDataAttributes instantiates a new EmailDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailDataAttributes(email string) *EmailDataAttributes {
	this := EmailDataAttributes{}
	this.Email = email
	return &this
}

// NewEmailDataAttributesWithDefaults instantiates a new EmailDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailDataAttributesWithDefaults() *EmailDataAttributes {
	this := EmailDataAttributes{}
	return &this
}

// GetEmail returns the Email field value
func (o *EmailDataAttributes) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *EmailDataAttributes) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *EmailDataAttributes) SetEmail(v string) {
	o.Email = v
}

func (o EmailDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmailDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	return toSerialize, nil
}

func (o *EmailDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmailDataAttributes := _EmailDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmailDataAttributes)

	if err != nil {
		return err
	}

	*o = EmailDataAttributes(varEmailDataAttributes)

	return err
}

type NullableEmailDataAttributes struct {
	value *EmailDataAttributes
	isSet bool
}

func (v NullableEmailDataAttributes) Get() *EmailDataAttributes {
	return v.value
}

func (v *NullableEmailDataAttributes) Set(val *EmailDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailDataAttributes(val *EmailDataAttributes) *NullableEmailDataAttributes {
	return &NullableEmailDataAttributes{value: val, isSet: true}
}

func (v NullableEmailDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


