/*
Example API

This is a sample API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RefreshResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RefreshResp{}

// RefreshResp struct for RefreshResp
type RefreshResp struct {
	Data RefreshRespData `json:"data"`
}

type _RefreshResp RefreshResp

// NewRefreshResp instantiates a new RefreshResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRefreshResp(data RefreshRespData) *RefreshResp {
	this := RefreshResp{}
	this.Data = data
	return &this
}

// NewRefreshRespWithDefaults instantiates a new RefreshResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRefreshRespWithDefaults() *RefreshResp {
	this := RefreshResp{}
	return &this
}

// GetData returns the Data field value
func (o *RefreshResp) GetData() RefreshRespData {
	if o == nil {
		var ret RefreshRespData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *RefreshResp) GetDataOk() (*RefreshRespData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *RefreshResp) SetData(v RefreshRespData) {
	o.Data = v
}

func (o RefreshResp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RefreshResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *RefreshResp) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRefreshResp := _RefreshResp{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRefreshResp)

	if err != nil {
		return err
	}

	*o = RefreshResp(varRefreshResp)

	return err
}

type NullableRefreshResp struct {
	value *RefreshResp
	isSet bool
}

func (v NullableRefreshResp) Get() *RefreshResp {
	return v.value
}

func (v *NullableRefreshResp) Set(val *RefreshResp) {
	v.value = val
	v.isSet = true
}

func (v NullableRefreshResp) IsSet() bool {
	return v.isSet
}

func (v *NullableRefreshResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRefreshResp(val *RefreshResp) *NullableRefreshResp {
	return &NullableRefreshResp{value: val, isSet: true}
}

func (v NullableRefreshResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRefreshResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


