/*
Example API

This is a sample API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the RegistrationAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegistrationAttributes{}

// RegistrationAttributes struct for RegistrationAttributes
type RegistrationAttributes struct {
	// Unique username
	Username *string `json:"username,omitempty"`
	// User email
	Email *string `json:"email,omitempty"`
	// User password
	Password *string `json:"password,omitempty"`
}

// NewRegistrationAttributes instantiates a new RegistrationAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegistrationAttributes() *RegistrationAttributes {
	this := RegistrationAttributes{}
	return &this
}

// NewRegistrationAttributesWithDefaults instantiates a new RegistrationAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegistrationAttributesWithDefaults() *RegistrationAttributes {
	this := RegistrationAttributes{}
	return &this
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *RegistrationAttributes) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistrationAttributes) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *RegistrationAttributes) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *RegistrationAttributes) SetUsername(v string) {
	o.Username = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *RegistrationAttributes) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistrationAttributes) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *RegistrationAttributes) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *RegistrationAttributes) SetEmail(v string) {
	o.Email = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *RegistrationAttributes) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistrationAttributes) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *RegistrationAttributes) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *RegistrationAttributes) SetPassword(v string) {
	o.Password = &v
}

func (o RegistrationAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegistrationAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	return toSerialize, nil
}

type NullableRegistrationAttributes struct {
	value *RegistrationAttributes
	isSet bool
}

func (v NullableRegistrationAttributes) Get() *RegistrationAttributes {
	return v.value
}

func (v *NullableRegistrationAttributes) Set(val *RegistrationAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableRegistrationAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableRegistrationAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegistrationAttributes(val *RegistrationAttributes) *NullableRegistrationAttributes {
	return &NullableRegistrationAttributes{value: val, isSet: true}
}

func (v NullableRegistrationAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegistrationAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


