/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TerminateSessionsDataAttributesDevicesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TerminateSessionsDataAttributesDevicesInner{}

// TerminateSessionsDataAttributesDevicesInner struct for TerminateSessionsDataAttributesDevicesInner
type TerminateSessionsDataAttributesDevicesInner struct {
	// Unique device identifier
	Id string `json:"id"`
}

type _TerminateSessionsDataAttributesDevicesInner TerminateSessionsDataAttributesDevicesInner

// NewTerminateSessionsDataAttributesDevicesInner instantiates a new TerminateSessionsDataAttributesDevicesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTerminateSessionsDataAttributesDevicesInner(id string) *TerminateSessionsDataAttributesDevicesInner {
	this := TerminateSessionsDataAttributesDevicesInner{}
	this.Id = id
	return &this
}

// NewTerminateSessionsDataAttributesDevicesInnerWithDefaults instantiates a new TerminateSessionsDataAttributesDevicesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTerminateSessionsDataAttributesDevicesInnerWithDefaults() *TerminateSessionsDataAttributesDevicesInner {
	this := TerminateSessionsDataAttributesDevicesInner{}
	return &this
}

// GetId returns the Id field value
func (o *TerminateSessionsDataAttributesDevicesInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *TerminateSessionsDataAttributesDevicesInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *TerminateSessionsDataAttributesDevicesInner) SetId(v string) {
	o.Id = v
}

func (o TerminateSessionsDataAttributesDevicesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TerminateSessionsDataAttributesDevicesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *TerminateSessionsDataAttributesDevicesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTerminateSessionsDataAttributesDevicesInner := _TerminateSessionsDataAttributesDevicesInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTerminateSessionsDataAttributesDevicesInner)

	if err != nil {
		return err
	}

	*o = TerminateSessionsDataAttributesDevicesInner(varTerminateSessionsDataAttributesDevicesInner)

	return err
}

type NullableTerminateSessionsDataAttributesDevicesInner struct {
	value *TerminateSessionsDataAttributesDevicesInner
	isSet bool
}

func (v NullableTerminateSessionsDataAttributesDevicesInner) Get() *TerminateSessionsDataAttributesDevicesInner {
	return v.value
}

func (v *NullableTerminateSessionsDataAttributesDevicesInner) Set(val *TerminateSessionsDataAttributesDevicesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableTerminateSessionsDataAttributesDevicesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableTerminateSessionsDataAttributesDevicesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTerminateSessionsDataAttributesDevicesInner(val *TerminateSessionsDataAttributesDevicesInner) *NullableTerminateSessionsDataAttributesDevicesInner {
	return &NullableTerminateSessionsDataAttributesDevicesInner{value: val, isSet: true}
}

func (v NullableTerminateSessionsDataAttributesDevicesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTerminateSessionsDataAttributesDevicesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


