/*
Example API

This is a sample API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LoginCompleteResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LoginCompleteResp{}

// LoginCompleteResp struct for LoginCompleteResp
type LoginCompleteResp struct {
	Data LoginCompleteRespData `json:"data"`
}

type _LoginCompleteResp LoginCompleteResp

// NewLoginCompleteResp instantiates a new LoginCompleteResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoginCompleteResp(data LoginCompleteRespData) *LoginCompleteResp {
	this := LoginCompleteResp{}
	this.Data = data
	return &this
}

// NewLoginCompleteRespWithDefaults instantiates a new LoginCompleteResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoginCompleteRespWithDefaults() *LoginCompleteResp {
	this := LoginCompleteResp{}
	return &this
}

// GetData returns the Data field value
func (o *LoginCompleteResp) GetData() LoginCompleteRespData {
	if o == nil {
		var ret LoginCompleteRespData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *LoginCompleteResp) GetDataOk() (*LoginCompleteRespData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *LoginCompleteResp) SetData(v LoginCompleteRespData) {
	o.Data = v
}

func (o LoginCompleteResp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LoginCompleteResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *LoginCompleteResp) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLoginCompleteResp := _LoginCompleteResp{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLoginCompleteResp)

	if err != nil {
		return err
	}

	*o = LoginCompleteResp(varLoginCompleteResp)

	return err
}

type NullableLoginCompleteResp struct {
	value *LoginCompleteResp
	isSet bool
}

func (v NullableLoginCompleteResp) Get() *LoginCompleteResp {
	return v.value
}

func (v *NullableLoginCompleteResp) Set(val *LoginCompleteResp) {
	v.value = val
	v.isSet = true
}

func (v NullableLoginCompleteResp) IsSet() bool {
	return v.isSet
}

func (v *NullableLoginCompleteResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoginCompleteResp(val *LoginCompleteResp) *NullableLoginCompleteResp {
	return &NullableLoginCompleteResp{value: val, isSet: true}
}

func (v NullableLoginCompleteResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoginCompleteResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


