/*
Example API

This is a sample API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RegistrationConfirmData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegistrationConfirmData{}

// RegistrationConfirmData struct for RegistrationConfirmData
type RegistrationConfirmData struct {
	// Unique identifier username
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes RegistrationConfirmDataAttributes `json:"attributes"`
}

type _RegistrationConfirmData RegistrationConfirmData

// NewRegistrationConfirmData instantiates a new RegistrationConfirmData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegistrationConfirmData(id string, type_ string, attributes RegistrationConfirmDataAttributes) *RegistrationConfirmData {
	this := RegistrationConfirmData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewRegistrationConfirmDataWithDefaults instantiates a new RegistrationConfirmData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegistrationConfirmDataWithDefaults() *RegistrationConfirmData {
	this := RegistrationConfirmData{}
	return &this
}

// GetId returns the Id field value
func (o *RegistrationConfirmData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RegistrationConfirmData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RegistrationConfirmData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *RegistrationConfirmData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *RegistrationConfirmData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *RegistrationConfirmData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *RegistrationConfirmData) GetAttributes() RegistrationConfirmDataAttributes {
	if o == nil {
		var ret RegistrationConfirmDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *RegistrationConfirmData) GetAttributesOk() (*RegistrationConfirmDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *RegistrationConfirmData) SetAttributes(v RegistrationConfirmDataAttributes) {
	o.Attributes = v
}

func (o RegistrationConfirmData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegistrationConfirmData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *RegistrationConfirmData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegistrationConfirmData := _RegistrationConfirmData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegistrationConfirmData)

	if err != nil {
		return err
	}

	*o = RegistrationConfirmData(varRegistrationConfirmData)

	return err
}

type NullableRegistrationConfirmData struct {
	value *RegistrationConfirmData
	isSet bool
}

func (v NullableRegistrationConfirmData) Get() *RegistrationConfirmData {
	return v.value
}

func (v *NullableRegistrationConfirmData) Set(val *RegistrationConfirmData) {
	v.value = val
	v.isSet = true
}

func (v NullableRegistrationConfirmData) IsSet() bool {
	return v.isSet
}

func (v *NullableRegistrationConfirmData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegistrationConfirmData(val *RegistrationConfirmData) *NullableRegistrationConfirmData {
	return &NullableRegistrationConfirmData{value: val, isSet: true}
}

func (v NullableRegistrationConfirmData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegistrationConfirmData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


