/*
Example API

This is a sample API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ActivateEmailDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ActivateEmailDataAttributes{}

// ActivateEmailDataAttributes struct for ActivateEmailDataAttributes
type ActivateEmailDataAttributes struct {
	// New email
	Email string `json:"email"`
	// User code
	Code string `json:"code"`
}

type _ActivateEmailDataAttributes ActivateEmailDataAttributes

// NewActivateEmailDataAttributes instantiates a new ActivateEmailDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActivateEmailDataAttributes(email string, code string) *ActivateEmailDataAttributes {
	this := ActivateEmailDataAttributes{}
	this.Email = email
	this.Code = code
	return &this
}

// NewActivateEmailDataAttributesWithDefaults instantiates a new ActivateEmailDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActivateEmailDataAttributesWithDefaults() *ActivateEmailDataAttributes {
	this := ActivateEmailDataAttributes{}
	return &this
}

// GetEmail returns the Email field value
func (o *ActivateEmailDataAttributes) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *ActivateEmailDataAttributes) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *ActivateEmailDataAttributes) SetEmail(v string) {
	o.Email = v
}

// GetCode returns the Code field value
func (o *ActivateEmailDataAttributes) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *ActivateEmailDataAttributes) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *ActivateEmailDataAttributes) SetCode(v string) {
	o.Code = v
}

func (o ActivateEmailDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ActivateEmailDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	toSerialize["code"] = o.Code
	return toSerialize, nil
}

func (o *ActivateEmailDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varActivateEmailDataAttributes := _ActivateEmailDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varActivateEmailDataAttributes)

	if err != nil {
		return err
	}

	*o = ActivateEmailDataAttributes(varActivateEmailDataAttributes)

	return err
}

type NullableActivateEmailDataAttributes struct {
	value *ActivateEmailDataAttributes
	isSet bool
}

func (v NullableActivateEmailDataAttributes) Get() *ActivateEmailDataAttributes {
	return v.value
}

func (v *NullableActivateEmailDataAttributes) Set(val *ActivateEmailDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableActivateEmailDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableActivateEmailDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActivateEmailDataAttributes(val *ActivateEmailDataAttributes) *NullableActivateEmailDataAttributes {
	return &NullableActivateEmailDataAttributes{value: val, isSet: true}
}

func (v NullableActivateEmailDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActivateEmailDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


