/*
Example API

This is a sample API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TerminateSessionsDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TerminateSessionsDataAttributes{}

// TerminateSessionsDataAttributes struct for TerminateSessionsDataAttributes
type TerminateSessionsDataAttributes struct {
	Devices []TerminateSessionsDataAttributesDevicesInner `json:"devices"`
}

type _TerminateSessionsDataAttributes TerminateSessionsDataAttributes

// NewTerminateSessionsDataAttributes instantiates a new TerminateSessionsDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTerminateSessionsDataAttributes(devices []TerminateSessionsDataAttributesDevicesInner) *TerminateSessionsDataAttributes {
	this := TerminateSessionsDataAttributes{}
	this.Devices = devices
	return &this
}

// NewTerminateSessionsDataAttributesWithDefaults instantiates a new TerminateSessionsDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTerminateSessionsDataAttributesWithDefaults() *TerminateSessionsDataAttributes {
	this := TerminateSessionsDataAttributes{}
	return &this
}

// GetDevices returns the Devices field value
func (o *TerminateSessionsDataAttributes) GetDevices() []TerminateSessionsDataAttributesDevicesInner {
	if o == nil {
		var ret []TerminateSessionsDataAttributesDevicesInner
		return ret
	}

	return o.Devices
}

// GetDevicesOk returns a tuple with the Devices field value
// and a boolean to check if the value has been set.
func (o *TerminateSessionsDataAttributes) GetDevicesOk() ([]TerminateSessionsDataAttributesDevicesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Devices, true
}

// SetDevices sets field value
func (o *TerminateSessionsDataAttributes) SetDevices(v []TerminateSessionsDataAttributesDevicesInner) {
	o.Devices = v
}

func (o TerminateSessionsDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TerminateSessionsDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["devices"] = o.Devices
	return toSerialize, nil
}

func (o *TerminateSessionsDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"devices",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTerminateSessionsDataAttributes := _TerminateSessionsDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTerminateSessionsDataAttributes)

	if err != nil {
		return err
	}

	*o = TerminateSessionsDataAttributes(varTerminateSessionsDataAttributes)

	return err
}

type NullableTerminateSessionsDataAttributes struct {
	value *TerminateSessionsDataAttributes
	isSet bool
}

func (v NullableTerminateSessionsDataAttributes) Get() *TerminateSessionsDataAttributes {
	return v.value
}

func (v *NullableTerminateSessionsDataAttributes) Set(val *TerminateSessionsDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableTerminateSessionsDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableTerminateSessionsDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTerminateSessionsDataAttributes(val *TerminateSessionsDataAttributes) *NullableTerminateSessionsDataAttributes {
	return &NullableTerminateSessionsDataAttributes{value: val, isSet: true}
}

func (v NullableTerminateSessionsDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTerminateSessionsDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


