/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RefreshRespDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RefreshRespDataAttributes{}

// RefreshRespDataAttributes struct for RefreshRespDataAttributes
type RefreshRespDataAttributes struct {
	// The new access token.
	AccessToken string `json:"access_token"`
	// The new refresh token.
	RefreshToken string `json:"refresh_token"`
}

type _RefreshRespDataAttributes RefreshRespDataAttributes

// NewRefreshRespDataAttributes instantiates a new RefreshRespDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRefreshRespDataAttributes(accessToken string, refreshToken string) *RefreshRespDataAttributes {
	this := RefreshRespDataAttributes{}
	this.AccessToken = accessToken
	this.RefreshToken = refreshToken
	return &this
}

// NewRefreshRespDataAttributesWithDefaults instantiates a new RefreshRespDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRefreshRespDataAttributesWithDefaults() *RefreshRespDataAttributes {
	this := RefreshRespDataAttributes{}
	return &this
}

// GetAccessToken returns the AccessToken field value
func (o *RefreshRespDataAttributes) GetAccessToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessToken
}

// GetAccessTokenOk returns a tuple with the AccessToken field value
// and a boolean to check if the value has been set.
func (o *RefreshRespDataAttributes) GetAccessTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessToken, true
}

// SetAccessToken sets field value
func (o *RefreshRespDataAttributes) SetAccessToken(v string) {
	o.AccessToken = v
}

// GetRefreshToken returns the RefreshToken field value
func (o *RefreshRespDataAttributes) GetRefreshToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RefreshToken
}

// GetRefreshTokenOk returns a tuple with the RefreshToken field value
// and a boolean to check if the value has been set.
func (o *RefreshRespDataAttributes) GetRefreshTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RefreshToken, true
}

// SetRefreshToken sets field value
func (o *RefreshRespDataAttributes) SetRefreshToken(v string) {
	o.RefreshToken = v
}

func (o RefreshRespDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RefreshRespDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["access_token"] = o.AccessToken
	toSerialize["refresh_token"] = o.RefreshToken
	return toSerialize, nil
}

func (o *RefreshRespDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"access_token",
		"refresh_token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRefreshRespDataAttributes := _RefreshRespDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRefreshRespDataAttributes)

	if err != nil {
		return err
	}

	*o = RefreshRespDataAttributes(varRefreshRespDataAttributes)

	return err
}

type NullableRefreshRespDataAttributes struct {
	value *RefreshRespDataAttributes
	isSet bool
}

func (v NullableRefreshRespDataAttributes) Get() *RefreshRespDataAttributes {
	return v.value
}

func (v *NullableRefreshRespDataAttributes) Set(val *RefreshRespDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableRefreshRespDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableRefreshRespDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRefreshRespDataAttributes(val *RefreshRespDataAttributes) *NullableRefreshRespDataAttributes {
	return &NullableRefreshRespDataAttributes{value: val, isSet: true}
}

func (v NullableRefreshRespDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRefreshRespDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


