/*
Example API

This is a sample API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RegistrationConfirmReqData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegistrationConfirmReqData{}

// RegistrationConfirmReqData struct for RegistrationConfirmReqData
type RegistrationConfirmReqData struct {
	// Unique identifier username
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes RegistrationConfirmReqDataAttributes `json:"attributes"`
}

type _RegistrationConfirmReqData RegistrationConfirmReqData

// NewRegistrationConfirmReqData instantiates a new RegistrationConfirmReqData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegistrationConfirmReqData(id string, type_ string, attributes RegistrationConfirmReqDataAttributes) *RegistrationConfirmReqData {
	this := RegistrationConfirmReqData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewRegistrationConfirmReqDataWithDefaults instantiates a new RegistrationConfirmReqData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegistrationConfirmReqDataWithDefaults() *RegistrationConfirmReqData {
	this := RegistrationConfirmReqData{}
	return &this
}

// GetId returns the Id field value
func (o *RegistrationConfirmReqData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RegistrationConfirmReqData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RegistrationConfirmReqData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *RegistrationConfirmReqData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *RegistrationConfirmReqData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *RegistrationConfirmReqData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *RegistrationConfirmReqData) GetAttributes() RegistrationConfirmReqDataAttributes {
	if o == nil {
		var ret RegistrationConfirmReqDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *RegistrationConfirmReqData) GetAttributesOk() (*RegistrationConfirmReqDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *RegistrationConfirmReqData) SetAttributes(v RegistrationConfirmReqDataAttributes) {
	o.Attributes = v
}

func (o RegistrationConfirmReqData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegistrationConfirmReqData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *RegistrationConfirmReqData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegistrationConfirmReqData := _RegistrationConfirmReqData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegistrationConfirmReqData)

	if err != nil {
		return err
	}

	*o = RegistrationConfirmReqData(varRegistrationConfirmReqData)

	return err
}

type NullableRegistrationConfirmReqData struct {
	value *RegistrationConfirmReqData
	isSet bool
}

func (v NullableRegistrationConfirmReqData) Get() *RegistrationConfirmReqData {
	return v.value
}

func (v *NullableRegistrationConfirmReqData) Set(val *RegistrationConfirmReqData) {
	v.value = val
	v.isSet = true
}

func (v NullableRegistrationConfirmReqData) IsSet() bool {
	return v.isSet
}

func (v *NullableRegistrationConfirmReqData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegistrationConfirmReqData(val *RegistrationConfirmReqData) *NullableRegistrationConfirmReqData {
	return &NullableRegistrationConfirmReqData{value: val, isSet: true}
}

func (v NullableRegistrationConfirmReqData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegistrationConfirmReqData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


