/*
Example API

This is a sample API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LoginInitiateData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LoginInitiateData{}

// LoginInitiateData struct for LoginInitiateData
type LoginInitiateData struct {
	Type string `json:"type"`
	Attributes LoginInitiateDataAttributes `json:"attributes"`
}

type _LoginInitiateData LoginInitiateData

// NewLoginInitiateData instantiates a new LoginInitiateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoginInitiateData(type_ string, attributes LoginInitiateDataAttributes) *LoginInitiateData {
	this := LoginInitiateData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewLoginInitiateDataWithDefaults instantiates a new LoginInitiateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoginInitiateDataWithDefaults() *LoginInitiateData {
	this := LoginInitiateData{}
	return &this
}

// GetType returns the Type field value
func (o *LoginInitiateData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *LoginInitiateData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *LoginInitiateData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *LoginInitiateData) GetAttributes() LoginInitiateDataAttributes {
	if o == nil {
		var ret LoginInitiateDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *LoginInitiateData) GetAttributesOk() (*LoginInitiateDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *LoginInitiateData) SetAttributes(v LoginInitiateDataAttributes) {
	o.Attributes = v
}

func (o LoginInitiateData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LoginInitiateData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *LoginInitiateData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLoginInitiateData := _LoginInitiateData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLoginInitiateData)

	if err != nil {
		return err
	}

	*o = LoginInitiateData(varLoginInitiateData)

	return err
}

type NullableLoginInitiateData struct {
	value *LoginInitiateData
	isSet bool
}

func (v NullableLoginInitiateData) Get() *LoginInitiateData {
	return v.value
}

func (v *NullableLoginInitiateData) Set(val *LoginInitiateData) {
	v.value = val
	v.isSet = true
}

func (v NullableLoginInitiateData) IsSet() bool {
	return v.isSet
}

func (v *NullableLoginInitiateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoginInitiateData(val *LoginInitiateData) *NullableLoginInitiateData {
	return &NullableLoginInitiateData{value: val, isSet: true}
}

func (v NullableLoginInitiateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoginInitiateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


