/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SessionsData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SessionsData{}

// SessionsData struct for SessionsData
type SessionsData struct {
	Type string `json:"type"`
	Attributes SessionsDataAttributes `json:"attributes"`
}

type _SessionsData SessionsData

// NewSessionsData instantiates a new SessionsData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSessionsData(type_ string, attributes SessionsDataAttributes) *SessionsData {
	this := SessionsData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewSessionsDataWithDefaults instantiates a new SessionsData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSessionsDataWithDefaults() *SessionsData {
	this := SessionsData{}
	return &this
}

// GetType returns the Type field value
func (o *SessionsData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SessionsData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SessionsData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *SessionsData) GetAttributes() SessionsDataAttributes {
	if o == nil {
		var ret SessionsDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *SessionsData) GetAttributesOk() (*SessionsDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *SessionsData) SetAttributes(v SessionsDataAttributes) {
	o.Attributes = v
}

func (o SessionsData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SessionsData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *SessionsData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSessionsData := _SessionsData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSessionsData)

	if err != nil {
		return err
	}

	*o = SessionsData(varSessionsData)

	return err
}

type NullableSessionsData struct {
	value *SessionsData
	isSet bool
}

func (v NullableSessionsData) Get() *SessionsData {
	return v.value
}

func (v *NullableSessionsData) Set(val *SessionsData) {
	v.value = val
	v.isSet = true
}

func (v NullableSessionsData) IsSet() bool {
	return v.isSet
}

func (v *NullableSessionsData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSessionsData(val *SessionsData) *NullableSessionsData {
	return &NullableSessionsData{value: val, isSet: true}
}

func (v NullableSessionsData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSessionsData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


