/*
Example API

This is a sample API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the UserSessionDataAttributesDevicesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserSessionDataAttributesDevicesInner{}

// UserSessionDataAttributesDevicesInner struct for UserSessionDataAttributesDevicesInner
type UserSessionDataAttributesDevicesInner struct {
	// Уникальный идентификатор устройства
	Id string `json:"id"`
	// Серийный номер устройства
	FactoryId string `json:"factory_id"`
	// Имя устройства, заданное пользователем
	DeviceName string `json:"device_name"`
	// Версия операционной системы устройства
	OsVersion string `json:"os_version"`
	// Дата и время последнего использования устройства
	LastUsed time.Time `json:"last_used"`
}

type _UserSessionDataAttributesDevicesInner UserSessionDataAttributesDevicesInner

// NewUserSessionDataAttributesDevicesInner instantiates a new UserSessionDataAttributesDevicesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserSessionDataAttributesDevicesInner(id string, factoryId string, deviceName string, osVersion string, lastUsed time.Time) *UserSessionDataAttributesDevicesInner {
	this := UserSessionDataAttributesDevicesInner{}
	this.Id = id
	this.FactoryId = factoryId
	this.DeviceName = deviceName
	this.OsVersion = osVersion
	this.LastUsed = lastUsed
	return &this
}

// NewUserSessionDataAttributesDevicesInnerWithDefaults instantiates a new UserSessionDataAttributesDevicesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserSessionDataAttributesDevicesInnerWithDefaults() *UserSessionDataAttributesDevicesInner {
	this := UserSessionDataAttributesDevicesInner{}
	return &this
}

// GetId returns the Id field value
func (o *UserSessionDataAttributesDevicesInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UserSessionDataAttributesDevicesInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UserSessionDataAttributesDevicesInner) SetId(v string) {
	o.Id = v
}

// GetFactoryId returns the FactoryId field value
func (o *UserSessionDataAttributesDevicesInner) GetFactoryId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FactoryId
}

// GetFactoryIdOk returns a tuple with the FactoryId field value
// and a boolean to check if the value has been set.
func (o *UserSessionDataAttributesDevicesInner) GetFactoryIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FactoryId, true
}

// SetFactoryId sets field value
func (o *UserSessionDataAttributesDevicesInner) SetFactoryId(v string) {
	o.FactoryId = v
}

// GetDeviceName returns the DeviceName field value
func (o *UserSessionDataAttributesDevicesInner) GetDeviceName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeviceName
}

// GetDeviceNameOk returns a tuple with the DeviceName field value
// and a boolean to check if the value has been set.
func (o *UserSessionDataAttributesDevicesInner) GetDeviceNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceName, true
}

// SetDeviceName sets field value
func (o *UserSessionDataAttributesDevicesInner) SetDeviceName(v string) {
	o.DeviceName = v
}

// GetOsVersion returns the OsVersion field value
func (o *UserSessionDataAttributesDevicesInner) GetOsVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OsVersion
}

// GetOsVersionOk returns a tuple with the OsVersion field value
// and a boolean to check if the value has been set.
func (o *UserSessionDataAttributesDevicesInner) GetOsVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OsVersion, true
}

// SetOsVersion sets field value
func (o *UserSessionDataAttributesDevicesInner) SetOsVersion(v string) {
	o.OsVersion = v
}

// GetLastUsed returns the LastUsed field value
func (o *UserSessionDataAttributesDevicesInner) GetLastUsed() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.LastUsed
}

// GetLastUsedOk returns a tuple with the LastUsed field value
// and a boolean to check if the value has been set.
func (o *UserSessionDataAttributesDevicesInner) GetLastUsedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastUsed, true
}

// SetLastUsed sets field value
func (o *UserSessionDataAttributesDevicesInner) SetLastUsed(v time.Time) {
	o.LastUsed = v
}

func (o UserSessionDataAttributesDevicesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserSessionDataAttributesDevicesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["factory_id"] = o.FactoryId
	toSerialize["device_name"] = o.DeviceName
	toSerialize["os_version"] = o.OsVersion
	toSerialize["last_used"] = o.LastUsed
	return toSerialize, nil
}

func (o *UserSessionDataAttributesDevicesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"factory_id",
		"device_name",
		"os_version",
		"last_used",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserSessionDataAttributesDevicesInner := _UserSessionDataAttributesDevicesInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserSessionDataAttributesDevicesInner)

	if err != nil {
		return err
	}

	*o = UserSessionDataAttributesDevicesInner(varUserSessionDataAttributesDevicesInner)

	return err
}

type NullableUserSessionDataAttributesDevicesInner struct {
	value *UserSessionDataAttributesDevicesInner
	isSet bool
}

func (v NullableUserSessionDataAttributesDevicesInner) Get() *UserSessionDataAttributesDevicesInner {
	return v.value
}

func (v *NullableUserSessionDataAttributesDevicesInner) Set(val *UserSessionDataAttributesDevicesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableUserSessionDataAttributesDevicesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableUserSessionDataAttributesDevicesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserSessionDataAttributesDevicesInner(val *UserSessionDataAttributesDevicesInner) *NullableUserSessionDataAttributesDevicesInner {
	return &NullableUserSessionDataAttributesDevicesInner{value: val, isSet: true}
}

func (v NullableUserSessionDataAttributesDevicesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserSessionDataAttributesDevicesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


