/*
Example API

This is a sample API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ResetPasswordInitiateDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResetPasswordInitiateDataAttributes{}

// ResetPasswordInitiateDataAttributes struct for ResetPasswordInitiateDataAttributes
type ResetPasswordInitiateDataAttributes struct {
	// User email (required if username is not provided).
	Email *string `json:"email,omitempty"`
	// User username (required if email is not provided).
	Username *string `json:"username,omitempty"`
	// Human-readable name for the user's device (e.g., 'iPhone 14').
	DeviceName string `json:"device_name"`
	// Operating system version of the user's device.
	OsVersion string `json:"os_version"`
}

type _ResetPasswordInitiateDataAttributes ResetPasswordInitiateDataAttributes

// NewResetPasswordInitiateDataAttributes instantiates a new ResetPasswordInitiateDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResetPasswordInitiateDataAttributes(deviceName string, osVersion string) *ResetPasswordInitiateDataAttributes {
	this := ResetPasswordInitiateDataAttributes{}
	this.DeviceName = deviceName
	this.OsVersion = osVersion
	return &this
}

// NewResetPasswordInitiateDataAttributesWithDefaults instantiates a new ResetPasswordInitiateDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResetPasswordInitiateDataAttributesWithDefaults() *ResetPasswordInitiateDataAttributes {
	this := ResetPasswordInitiateDataAttributes{}
	return &this
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *ResetPasswordInitiateDataAttributes) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResetPasswordInitiateDataAttributes) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *ResetPasswordInitiateDataAttributes) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *ResetPasswordInitiateDataAttributes) SetEmail(v string) {
	o.Email = &v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *ResetPasswordInitiateDataAttributes) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResetPasswordInitiateDataAttributes) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *ResetPasswordInitiateDataAttributes) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *ResetPasswordInitiateDataAttributes) SetUsername(v string) {
	o.Username = &v
}

// GetDeviceName returns the DeviceName field value
func (o *ResetPasswordInitiateDataAttributes) GetDeviceName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeviceName
}

// GetDeviceNameOk returns a tuple with the DeviceName field value
// and a boolean to check if the value has been set.
func (o *ResetPasswordInitiateDataAttributes) GetDeviceNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceName, true
}

// SetDeviceName sets field value
func (o *ResetPasswordInitiateDataAttributes) SetDeviceName(v string) {
	o.DeviceName = v
}

// GetOsVersion returns the OsVersion field value
func (o *ResetPasswordInitiateDataAttributes) GetOsVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OsVersion
}

// GetOsVersionOk returns a tuple with the OsVersion field value
// and a boolean to check if the value has been set.
func (o *ResetPasswordInitiateDataAttributes) GetOsVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OsVersion, true
}

// SetOsVersion sets field value
func (o *ResetPasswordInitiateDataAttributes) SetOsVersion(v string) {
	o.OsVersion = v
}

func (o ResetPasswordInitiateDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResetPasswordInitiateDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	toSerialize["device_name"] = o.DeviceName
	toSerialize["os_version"] = o.OsVersion
	return toSerialize, nil
}

func (o *ResetPasswordInitiateDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"device_name",
		"os_version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResetPasswordInitiateDataAttributes := _ResetPasswordInitiateDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResetPasswordInitiateDataAttributes)

	if err != nil {
		return err
	}

	*o = ResetPasswordInitiateDataAttributes(varResetPasswordInitiateDataAttributes)

	return err
}

type NullableResetPasswordInitiateDataAttributes struct {
	value *ResetPasswordInitiateDataAttributes
	isSet bool
}

func (v NullableResetPasswordInitiateDataAttributes) Get() *ResetPasswordInitiateDataAttributes {
	return v.value
}

func (v *NullableResetPasswordInitiateDataAttributes) Set(val *ResetPasswordInitiateDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableResetPasswordInitiateDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableResetPasswordInitiateDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResetPasswordInitiateDataAttributes(val *ResetPasswordInitiateDataAttributes) *NullableResetPasswordInitiateDataAttributes {
	return &NullableResetPasswordInitiateDataAttributes{value: val, isSet: true}
}

func (v NullableResetPasswordInitiateDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResetPasswordInitiateDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


