/*
Example API

This is a sample API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ResetPasswordComplete type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResetPasswordComplete{}

// ResetPasswordComplete struct for ResetPasswordComplete
type ResetPasswordComplete struct {
	Data ResetPasswordCompleteData `json:"data"`
}

type _ResetPasswordComplete ResetPasswordComplete

// NewResetPasswordComplete instantiates a new ResetPasswordComplete object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResetPasswordComplete(data ResetPasswordCompleteData) *ResetPasswordComplete {
	this := ResetPasswordComplete{}
	this.Data = data
	return &this
}

// NewResetPasswordCompleteWithDefaults instantiates a new ResetPasswordComplete object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResetPasswordCompleteWithDefaults() *ResetPasswordComplete {
	this := ResetPasswordComplete{}
	return &this
}

// GetData returns the Data field value
func (o *ResetPasswordComplete) GetData() ResetPasswordCompleteData {
	if o == nil {
		var ret ResetPasswordCompleteData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ResetPasswordComplete) GetDataOk() (*ResetPasswordCompleteData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ResetPasswordComplete) SetData(v ResetPasswordCompleteData) {
	o.Data = v
}

func (o ResetPasswordComplete) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResetPasswordComplete) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ResetPasswordComplete) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResetPasswordComplete := _ResetPasswordComplete{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResetPasswordComplete)

	if err != nil {
		return err
	}

	*o = ResetPasswordComplete(varResetPasswordComplete)

	return err
}

type NullableResetPasswordComplete struct {
	value *ResetPasswordComplete
	isSet bool
}

func (v NullableResetPasswordComplete) Get() *ResetPasswordComplete {
	return v.value
}

func (v *NullableResetPasswordComplete) Set(val *ResetPasswordComplete) {
	v.value = val
	v.isSet = true
}

func (v NullableResetPasswordComplete) IsSet() bool {
	return v.isSet
}

func (v *NullableResetPasswordComplete) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResetPasswordComplete(val *ResetPasswordComplete) *NullableResetPasswordComplete {
	return &NullableResetPasswordComplete{value: val, isSet: true}
}

func (v NullableResetPasswordComplete) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResetPasswordComplete) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


