/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RefreshTokenDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RefreshTokenDataAttributes{}

// RefreshTokenDataAttributes struct for RefreshTokenDataAttributes
type RefreshTokenDataAttributes struct {
	// The refresh token to generate a new access token.
	RefreshToken string `json:"refresh_token"`
}

type _RefreshTokenDataAttributes RefreshTokenDataAttributes

// NewRefreshTokenDataAttributes instantiates a new RefreshTokenDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRefreshTokenDataAttributes(refreshToken string) *RefreshTokenDataAttributes {
	this := RefreshTokenDataAttributes{}
	this.RefreshToken = refreshToken
	return &this
}

// NewRefreshTokenDataAttributesWithDefaults instantiates a new RefreshTokenDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRefreshTokenDataAttributesWithDefaults() *RefreshTokenDataAttributes {
	this := RefreshTokenDataAttributes{}
	return &this
}

// GetRefreshToken returns the RefreshToken field value
func (o *RefreshTokenDataAttributes) GetRefreshToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RefreshToken
}

// GetRefreshTokenOk returns a tuple with the RefreshToken field value
// and a boolean to check if the value has been set.
func (o *RefreshTokenDataAttributes) GetRefreshTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RefreshToken, true
}

// SetRefreshToken sets field value
func (o *RefreshTokenDataAttributes) SetRefreshToken(v string) {
	o.RefreshToken = v
}

func (o RefreshTokenDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RefreshTokenDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["refresh_token"] = o.RefreshToken
	return toSerialize, nil
}

func (o *RefreshTokenDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"refresh_token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRefreshTokenDataAttributes := _RefreshTokenDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRefreshTokenDataAttributes)

	if err != nil {
		return err
	}

	*o = RefreshTokenDataAttributes(varRefreshTokenDataAttributes)

	return err
}

type NullableRefreshTokenDataAttributes struct {
	value *RefreshTokenDataAttributes
	isSet bool
}

func (v NullableRefreshTokenDataAttributes) Get() *RefreshTokenDataAttributes {
	return v.value
}

func (v *NullableRefreshTokenDataAttributes) Set(val *RefreshTokenDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableRefreshTokenDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableRefreshTokenDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRefreshTokenDataAttributes(val *RefreshTokenDataAttributes) *NullableRefreshTokenDataAttributes {
	return &NullableRefreshTokenDataAttributes{value: val, isSet: true}
}

func (v NullableRefreshTokenDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRefreshTokenDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


