/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CredentialsDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CredentialsDataAttributes{}

// CredentialsDataAttributes struct for CredentialsDataAttributes
type CredentialsDataAttributes struct {
	// User email (required if username is not provided)
	Email string `json:"email"`
	// New user password
	Password string `json:"password"`
}

type _CredentialsDataAttributes CredentialsDataAttributes

// NewCredentialsDataAttributes instantiates a new CredentialsDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCredentialsDataAttributes(email string, password string) *CredentialsDataAttributes {
	this := CredentialsDataAttributes{}
	this.Email = email
	this.Password = password
	return &this
}

// NewCredentialsDataAttributesWithDefaults instantiates a new CredentialsDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCredentialsDataAttributesWithDefaults() *CredentialsDataAttributes {
	this := CredentialsDataAttributes{}
	return &this
}

// GetEmail returns the Email field value
func (o *CredentialsDataAttributes) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *CredentialsDataAttributes) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *CredentialsDataAttributes) SetEmail(v string) {
	o.Email = v
}

// GetPassword returns the Password field value
func (o *CredentialsDataAttributes) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *CredentialsDataAttributes) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *CredentialsDataAttributes) SetPassword(v string) {
	o.Password = v
}

func (o CredentialsDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CredentialsDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	toSerialize["password"] = o.Password
	return toSerialize, nil
}

func (o *CredentialsDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCredentialsDataAttributes := _CredentialsDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCredentialsDataAttributes)

	if err != nil {
		return err
	}

	*o = CredentialsDataAttributes(varCredentialsDataAttributes)

	return err
}

type NullableCredentialsDataAttributes struct {
	value *CredentialsDataAttributes
	isSet bool
}

func (v NullableCredentialsDataAttributes) Get() *CredentialsDataAttributes {
	return v.value
}

func (v *NullableCredentialsDataAttributes) Set(val *CredentialsDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableCredentialsDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableCredentialsDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCredentialsDataAttributes(val *CredentialsDataAttributes) *NullableCredentialsDataAttributes {
	return &NullableCredentialsDataAttributes{value: val, isSet: true}
}

func (v NullableCredentialsDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCredentialsDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


