/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ResetPasswordInitiateData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResetPasswordInitiateData{}

// ResetPasswordInitiateData struct for ResetPasswordInitiateData
type ResetPasswordInitiateData struct {
	Type string `json:"type"`
	Attributes ResetPasswordInitiateDataAttributes `json:"attributes"`
}

type _ResetPasswordInitiateData ResetPasswordInitiateData

// NewResetPasswordInitiateData instantiates a new ResetPasswordInitiateData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResetPasswordInitiateData(type_ string, attributes ResetPasswordInitiateDataAttributes) *ResetPasswordInitiateData {
	this := ResetPasswordInitiateData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewResetPasswordInitiateDataWithDefaults instantiates a new ResetPasswordInitiateData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResetPasswordInitiateDataWithDefaults() *ResetPasswordInitiateData {
	this := ResetPasswordInitiateData{}
	return &this
}

// GetType returns the Type field value
func (o *ResetPasswordInitiateData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ResetPasswordInitiateData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ResetPasswordInitiateData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *ResetPasswordInitiateData) GetAttributes() ResetPasswordInitiateDataAttributes {
	if o == nil {
		var ret ResetPasswordInitiateDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *ResetPasswordInitiateData) GetAttributesOk() (*ResetPasswordInitiateDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *ResetPasswordInitiateData) SetAttributes(v ResetPasswordInitiateDataAttributes) {
	o.Attributes = v
}

func (o ResetPasswordInitiateData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResetPasswordInitiateData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *ResetPasswordInitiateData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResetPasswordInitiateData := _ResetPasswordInitiateData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResetPasswordInitiateData)

	if err != nil {
		return err
	}

	*o = ResetPasswordInitiateData(varResetPasswordInitiateData)

	return err
}

type NullableResetPasswordInitiateData struct {
	value *ResetPasswordInitiateData
	isSet bool
}

func (v NullableResetPasswordInitiateData) Get() *ResetPasswordInitiateData {
	return v.value
}

func (v *NullableResetPasswordInitiateData) Set(val *ResetPasswordInitiateData) {
	v.value = val
	v.isSet = true
}

func (v NullableResetPasswordInitiateData) IsSet() bool {
	return v.isSet
}

func (v *NullableResetPasswordInitiateData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResetPasswordInitiateData(val *ResetPasswordInitiateData) *NullableResetPasswordInitiateData {
	return &NullableResetPasswordInitiateData{value: val, isSet: true}
}

func (v NullableResetPasswordInitiateData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResetPasswordInitiateData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


