/*
Example API

This is a sample API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ResetPasswordReqData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResetPasswordReqData{}

// ResetPasswordReqData struct for ResetPasswordReqData
type ResetPasswordReqData struct {
	Type string `json:"type"`
	Attributes ResetPasswordReqDataAttributes `json:"attributes"`
}

type _ResetPasswordReqData ResetPasswordReqData

// NewResetPasswordReqData instantiates a new ResetPasswordReqData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResetPasswordReqData(type_ string, attributes ResetPasswordReqDataAttributes) *ResetPasswordReqData {
	this := ResetPasswordReqData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewResetPasswordReqDataWithDefaults instantiates a new ResetPasswordReqData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResetPasswordReqDataWithDefaults() *ResetPasswordReqData {
	this := ResetPasswordReqData{}
	return &this
}

// GetType returns the Type field value
func (o *ResetPasswordReqData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ResetPasswordReqData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ResetPasswordReqData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *ResetPasswordReqData) GetAttributes() ResetPasswordReqDataAttributes {
	if o == nil {
		var ret ResetPasswordReqDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *ResetPasswordReqData) GetAttributesOk() (*ResetPasswordReqDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *ResetPasswordReqData) SetAttributes(v ResetPasswordReqDataAttributes) {
	o.Attributes = v
}

func (o ResetPasswordReqData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResetPasswordReqData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *ResetPasswordReqData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResetPasswordReqData := _ResetPasswordReqData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResetPasswordReqData)

	if err != nil {
		return err
	}

	*o = ResetPasswordReqData(varResetPasswordReqData)

	return err
}

type NullableResetPasswordReqData struct {
	value *ResetPasswordReqData
	isSet bool
}

func (v NullableResetPasswordReqData) Get() *ResetPasswordReqData {
	return v.value
}

func (v *NullableResetPasswordReqData) Set(val *ResetPasswordReqData) {
	v.value = val
	v.isSet = true
}

func (v NullableResetPasswordReqData) IsSet() bool {
	return v.isSet
}

func (v *NullableResetPasswordReqData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResetPasswordReqData(val *ResetPasswordReqData) *NullableResetPasswordReqData {
	return &NullableResetPasswordReqData{value: val, isSet: true}
}

func (v NullableResetPasswordReqData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResetPasswordReqData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


