/*
Example API

This is a sample API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RegistrationInitiate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegistrationInitiate{}

// RegistrationInitiate struct for RegistrationInitiate
type RegistrationInitiate struct {
	Data RegistrationInitiateData `json:"data"`
}

type _RegistrationInitiate RegistrationInitiate

// NewRegistrationInitiate instantiates a new RegistrationInitiate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegistrationInitiate(data RegistrationInitiateData) *RegistrationInitiate {
	this := RegistrationInitiate{}
	this.Data = data
	return &this
}

// NewRegistrationInitiateWithDefaults instantiates a new RegistrationInitiate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegistrationInitiateWithDefaults() *RegistrationInitiate {
	this := RegistrationInitiate{}
	return &this
}

// GetData returns the Data field value
func (o *RegistrationInitiate) GetData() RegistrationInitiateData {
	if o == nil {
		var ret RegistrationInitiateData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *RegistrationInitiate) GetDataOk() (*RegistrationInitiateData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *RegistrationInitiate) SetData(v RegistrationInitiateData) {
	o.Data = v
}

func (o RegistrationInitiate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegistrationInitiate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *RegistrationInitiate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegistrationInitiate := _RegistrationInitiate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegistrationInitiate)

	if err != nil {
		return err
	}

	*o = RegistrationInitiate(varRegistrationInitiate)

	return err
}

type NullableRegistrationInitiate struct {
	value *RegistrationInitiate
	isSet bool
}

func (v NullableRegistrationInitiate) Get() *RegistrationInitiate {
	return v.value
}

func (v *NullableRegistrationInitiate) Set(val *RegistrationInitiate) {
	v.value = val
	v.isSet = true
}

func (v NullableRegistrationInitiate) IsSet() bool {
	return v.isSet
}

func (v *NullableRegistrationInitiate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegistrationInitiate(val *RegistrationInitiate) *NullableRegistrationInitiate {
	return &NullableRegistrationInitiate{value: val, isSet: true}
}

func (v NullableRegistrationInitiate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegistrationInitiate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


