/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OperationData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OperationData{}

// OperationData struct for OperationData
type OperationData struct {
	Data OperationDataData `json:"data"`
}

type _OperationData OperationData

// NewOperationData instantiates a new OperationData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOperationData(data OperationDataData) *OperationData {
	this := OperationData{}
	this.Data = data
	return &this
}

// NewOperationDataWithDefaults instantiates a new OperationData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOperationDataWithDefaults() *OperationData {
	this := OperationData{}
	return &this
}

// GetData returns the Data field value
func (o *OperationData) GetData() OperationDataData {
	if o == nil {
		var ret OperationDataData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *OperationData) GetDataOk() (*OperationDataData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *OperationData) SetData(v OperationDataData) {
	o.Data = v
}

func (o OperationData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OperationData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *OperationData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOperationData := _OperationData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOperationData)

	if err != nil {
		return err
	}

	*o = OperationData(varOperationData)

	return err
}

type NullableOperationData struct {
	value *OperationData
	isSet bool
}

func (v NullableOperationData) Get() *OperationData {
	return v.value
}

func (v *NullableOperationData) Set(val *OperationData) {
	v.value = val
	v.isSet = true
}

func (v NullableOperationData) IsSet() bool {
	return v.isSet
}

func (v *NullableOperationData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperationData(val *OperationData) *NullableOperationData {
	return &NullableOperationData{value: val, isSet: true}
}

func (v NullableOperationData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperationData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


