/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApproveOperationDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApproveOperationDataAttributes{}

// ApproveOperationDataAttributes struct for ApproveOperationDataAttributes
type ApproveOperationDataAttributes struct {
	// New email
	Email string `json:"email"`
	// User code
	Code string `json:"code"`
	// Type of operation
	Operation string `json:"operation"`
}

type _ApproveOperationDataAttributes ApproveOperationDataAttributes

// NewApproveOperationDataAttributes instantiates a new ApproveOperationDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApproveOperationDataAttributes(email string, code string, operation string) *ApproveOperationDataAttributes {
	this := ApproveOperationDataAttributes{}
	this.Email = email
	this.Code = code
	this.Operation = operation
	return &this
}

// NewApproveOperationDataAttributesWithDefaults instantiates a new ApproveOperationDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApproveOperationDataAttributesWithDefaults() *ApproveOperationDataAttributes {
	this := ApproveOperationDataAttributes{}
	return &this
}

// GetEmail returns the Email field value
func (o *ApproveOperationDataAttributes) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *ApproveOperationDataAttributes) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *ApproveOperationDataAttributes) SetEmail(v string) {
	o.Email = v
}

// GetCode returns the Code field value
func (o *ApproveOperationDataAttributes) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *ApproveOperationDataAttributes) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *ApproveOperationDataAttributes) SetCode(v string) {
	o.Code = v
}

// GetOperation returns the Operation field value
func (o *ApproveOperationDataAttributes) GetOperation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Operation
}

// GetOperationOk returns a tuple with the Operation field value
// and a boolean to check if the value has been set.
func (o *ApproveOperationDataAttributes) GetOperationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Operation, true
}

// SetOperation sets field value
func (o *ApproveOperationDataAttributes) SetOperation(v string) {
	o.Operation = v
}

func (o ApproveOperationDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApproveOperationDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	toSerialize["code"] = o.Code
	toSerialize["operation"] = o.Operation
	return toSerialize, nil
}

func (o *ApproveOperationDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"code",
		"operation",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApproveOperationDataAttributes := _ApproveOperationDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApproveOperationDataAttributes)

	if err != nil {
		return err
	}

	*o = ApproveOperationDataAttributes(varApproveOperationDataAttributes)

	return err
}

type NullableApproveOperationDataAttributes struct {
	value *ApproveOperationDataAttributes
	isSet bool
}

func (v NullableApproveOperationDataAttributes) Get() *ApproveOperationDataAttributes {
	return v.value
}

func (v *NullableApproveOperationDataAttributes) Set(val *ApproveOperationDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableApproveOperationDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableApproveOperationDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApproveOperationDataAttributes(val *ApproveOperationDataAttributes) *NullableApproveOperationDataAttributes {
	return &NullableApproveOperationDataAttributes{value: val, isSet: true}
}

func (v NullableApproveOperationDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApproveOperationDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


