/*
Example API

This is a sample API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RefreshRespData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RefreshRespData{}

// RefreshRespData struct for RefreshRespData
type RefreshRespData struct {
	Type string `json:"type"`
	Attributes RefreshRespDataAttributes `json:"attributes"`
}

type _RefreshRespData RefreshRespData

// NewRefreshRespData instantiates a new RefreshRespData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRefreshRespData(type_ string, attributes RefreshRespDataAttributes) *RefreshRespData {
	this := RefreshRespData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewRefreshRespDataWithDefaults instantiates a new RefreshRespData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRefreshRespDataWithDefaults() *RefreshRespData {
	this := RefreshRespData{}
	return &this
}

// GetType returns the Type field value
func (o *RefreshRespData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *RefreshRespData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *RefreshRespData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *RefreshRespData) GetAttributes() RefreshRespDataAttributes {
	if o == nil {
		var ret RefreshRespDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *RefreshRespData) GetAttributesOk() (*RefreshRespDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *RefreshRespData) SetAttributes(v RefreshRespDataAttributes) {
	o.Attributes = v
}

func (o RefreshRespData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RefreshRespData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *RefreshRespData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRefreshRespData := _RefreshRespData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRefreshRespData)

	if err != nil {
		return err
	}

	*o = RefreshRespData(varRefreshRespData)

	return err
}

type NullableRefreshRespData struct {
	value *RefreshRespData
	isSet bool
}

func (v NullableRefreshRespData) Get() *RefreshRespData {
	return v.value
}

func (v *NullableRefreshRespData) Set(val *RefreshRespData) {
	v.value = val
	v.isSet = true
}

func (v NullableRefreshRespData) IsSet() bool {
	return v.isSet
}

func (v *NullableRefreshRespData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRefreshRespData(val *RefreshRespData) *NullableRefreshRespData {
	return &NullableRefreshRespData{value: val, isSet: true}
}

func (v NullableRefreshRespData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRefreshRespData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


