/*
Example API

This is a sample API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RegistrationAllOfAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegistrationAllOfAttributes{}

// RegistrationAllOfAttributes struct for RegistrationAllOfAttributes
type RegistrationAllOfAttributes struct {
	// Unique username
	Username string `json:"username"`
	// User email
	Email string `json:"email"`
	// User password
	Password string `json:"password"`
}

type _RegistrationAllOfAttributes RegistrationAllOfAttributes

// NewRegistrationAllOfAttributes instantiates a new RegistrationAllOfAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegistrationAllOfAttributes(username string, email string, password string) *RegistrationAllOfAttributes {
	this := RegistrationAllOfAttributes{}
	this.Username = username
	this.Email = email
	this.Password = password
	return &this
}

// NewRegistrationAllOfAttributesWithDefaults instantiates a new RegistrationAllOfAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegistrationAllOfAttributesWithDefaults() *RegistrationAllOfAttributes {
	this := RegistrationAllOfAttributes{}
	return &this
}

// GetUsername returns the Username field value
func (o *RegistrationAllOfAttributes) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *RegistrationAllOfAttributes) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *RegistrationAllOfAttributes) SetUsername(v string) {
	o.Username = v
}

// GetEmail returns the Email field value
func (o *RegistrationAllOfAttributes) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *RegistrationAllOfAttributes) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *RegistrationAllOfAttributes) SetEmail(v string) {
	o.Email = v
}

// GetPassword returns the Password field value
func (o *RegistrationAllOfAttributes) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *RegistrationAllOfAttributes) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *RegistrationAllOfAttributes) SetPassword(v string) {
	o.Password = v
}

func (o RegistrationAllOfAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegistrationAllOfAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["username"] = o.Username
	toSerialize["email"] = o.Email
	toSerialize["password"] = o.Password
	return toSerialize, nil
}

func (o *RegistrationAllOfAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"username",
		"email",
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegistrationAllOfAttributes := _RegistrationAllOfAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegistrationAllOfAttributes)

	if err != nil {
		return err
	}

	*o = RegistrationAllOfAttributes(varRegistrationAllOfAttributes)

	return err
}

type NullableRegistrationAllOfAttributes struct {
	value *RegistrationAllOfAttributes
	isSet bool
}

func (v NullableRegistrationAllOfAttributes) Get() *RegistrationAllOfAttributes {
	return v.value
}

func (v *NullableRegistrationAllOfAttributes) Set(val *RegistrationAllOfAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableRegistrationAllOfAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableRegistrationAllOfAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegistrationAllOfAttributes(val *RegistrationAllOfAttributes) *NullableRegistrationAllOfAttributes {
	return &NullableRegistrationAllOfAttributes{value: val, isSet: true}
}

func (v NullableRegistrationAllOfAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegistrationAllOfAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


