/*
Example API

This is a sample API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LoginInitiateDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LoginInitiateDataAttributes{}

// LoginInitiateDataAttributes struct for LoginInitiateDataAttributes
type LoginInitiateDataAttributes struct {
	// User email
	Email *string `json:"email,omitempty"`
	// User username
	Username *string `json:"username,omitempty"`
	// First password
	Password string `json:"password"`
}

type _LoginInitiateDataAttributes LoginInitiateDataAttributes

// NewLoginInitiateDataAttributes instantiates a new LoginInitiateDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoginInitiateDataAttributes(password string) *LoginInitiateDataAttributes {
	this := LoginInitiateDataAttributes{}
	this.Password = password
	return &this
}

// NewLoginInitiateDataAttributesWithDefaults instantiates a new LoginInitiateDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoginInitiateDataAttributesWithDefaults() *LoginInitiateDataAttributes {
	this := LoginInitiateDataAttributes{}
	return &this
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *LoginInitiateDataAttributes) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoginInitiateDataAttributes) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *LoginInitiateDataAttributes) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *LoginInitiateDataAttributes) SetEmail(v string) {
	o.Email = &v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *LoginInitiateDataAttributes) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoginInitiateDataAttributes) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *LoginInitiateDataAttributes) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *LoginInitiateDataAttributes) SetUsername(v string) {
	o.Username = &v
}

// GetPassword returns the Password field value
func (o *LoginInitiateDataAttributes) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *LoginInitiateDataAttributes) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *LoginInitiateDataAttributes) SetPassword(v string) {
	o.Password = v
}

func (o LoginInitiateDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LoginInitiateDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	toSerialize["password"] = o.Password
	return toSerialize, nil
}

func (o *LoginInitiateDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLoginInitiateDataAttributes := _LoginInitiateDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLoginInitiateDataAttributes)

	if err != nil {
		return err
	}

	*o = LoginInitiateDataAttributes(varLoginInitiateDataAttributes)

	return err
}

type NullableLoginInitiateDataAttributes struct {
	value *LoginInitiateDataAttributes
	isSet bool
}

func (v NullableLoginInitiateDataAttributes) Get() *LoginInitiateDataAttributes {
	return v.value
}

func (v *NullableLoginInitiateDataAttributes) Set(val *LoginInitiateDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableLoginInitiateDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableLoginInitiateDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoginInitiateDataAttributes(val *LoginInitiateDataAttributes) *NullableLoginInitiateDataAttributes {
	return &NullableLoginInitiateDataAttributes{value: val, isSet: true}
}

func (v NullableLoginInitiateDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoginInitiateDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


