// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: operations.sql

package dbcore

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createOperation = `-- name: CreateOperation :exec
INSERT INTO operations (user_id, operation, device_data, success, failure_reason)
VALUES ($1, $2, $3, $4, $5)
`

type CreateOperationParams struct {
	UserID        uuid.UUID
	Operation     OperationType
	DeviceData    json.RawMessage
	Success       bool
	FailureReason NullFailureReason
}

func (q *Queries) CreateOperation(ctx context.Context, arg CreateOperationParams) error {
	_, err := q.db.ExecContext(ctx, createOperation,
		arg.UserID,
		arg.Operation,
		arg.DeviceData,
		arg.Success,
		arg.FailureReason,
	)
	return err
}
