// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package data

import (
	"github.com/google/uuid"
)

type UsersSecret struct {
	ID          uuid.UUID
	Username    string
	Email       string
	EmailStatus bool
	PassHash    string
}
