openapi: 3.0.0
info:
  description: This is a sample API.
  title: Example API
  version: 1.0.0
servers:
- url: /
paths:
  /registertion-initiate: {}
  /registration-complete: {}
  /aprove-operation: {}
  /login: {}
  /change-username: {}
  /refresh: {}
  /reset-password-initiate: {}
  /reset-password-complete: {}
components:
  schemas:
    RegistrationInitiate:
      properties:
        data:
          $ref: '#/components/schemas/RegistrationInitiate_data'
      required:
      - data
      type: object
    RegistrationComplete:
      properties:
        data:
          $ref: '#/components/schemas/RegistrationComplete_data'
      required:
      - data
      type: object
    ApproveOperationReq:
      properties:
        data:
          $ref: '#/components/schemas/ApproveOperationReq_data'
      required:
      - data
      type: object
    LoginReq:
      properties:
        data:
          $ref: '#/components/schemas/LoginReq_data'
      required:
      - data
      type: object
    LoginResp:
      properties:
        data:
          $ref: '#/components/schemas/LoginResp_data'
      required:
      - data
      type: object
    ResetPasswordInitiate:
      properties:
        data:
          $ref: '#/components/schemas/ResetPasswordInitiate_data'
      required:
      - data
      type: object
    ResetPasswordComplete:
      properties:
        data:
          $ref: '#/components/schemas/ResetPasswordComplete_data'
      required:
      - data
      type: object
    ChangeUsernameReq:
      properties:
        data:
          $ref: '#/components/schemas/ChangeUsernameReq_data'
      required:
      - data
      type: object
    RefreshReq:
      properties:
        data:
          $ref: '#/components/schemas/RefreshReq_data'
      required:
      - data
      type: object
    RefreshResp:
      properties:
        data:
          $ref: '#/components/schemas/RefreshResp_data'
      required:
      - data
      type: object
    RegistrationInitiate_data_attributes:
      properties:
        email:
          description: User email
          format: email
          type: string
        username:
          description: User username
          type: string
      required:
      - email
      - username
      type: object
    RegistrationInitiate_data:
      properties:
        type:
          enum:
          - registration
          type: string
        attributes:
          $ref: '#/components/schemas/RegistrationInitiate_data_attributes'
      required:
      - attributes
      - type
      type: object
    RegistrationComplete_data_attributes:
      properties:
        first_password:
          description: First password
          type: string
        second_password:
          description: Second password
          type: string
        email:
          description: User email
          format: email
          type: string
        username:
          description: User username
          type: string
      required:
      - email
      - first_password
      - password
      - second_password
      type: object
    RegistrationComplete_data:
      properties:
        type:
          enum:
          - registration_complete
          type: string
        attributes:
          $ref: '#/components/schemas/RegistrationComplete_data_attributes'
      required:
      - attributes
      - type
      type: object
    ApproveOperationReq_data_attributes:
      properties:
        email:
          description: New email
          type: string
        code:
          description: User code
          type: string
        operation:
          description: Type of operation
          example: reset_password
          type: string
      required:
      - code
      - email
      - operation
      type: object
    ApproveOperationReq_data:
      properties:
        type:
          enum:
          - approve_operation
          type: string
        attributes:
          $ref: '#/components/schemas/ApproveOperationReq_data_attributes'
      required:
      - attributes
      - type
      type: object
    LoginReq_data_attributes:
      properties:
        email:
          description: User email (required if username is not provided).
          format: email
          type: string
        username:
          description: User username (required if email is not provided).
          type: string
        password:
          description: User password.
          type: string
        factory_id:
          description: Unique identifier for the user's device.
          type: string
        device_name:
          description: "Human-readable name for the user's device (e.g., 'iPhone 14')."
          type: string
        os_version:
          description: Operating system version of the user's device.
          type: string
      required:
      - device_name
      - factory_id
      - os_version
      - password
      type: object
    LoginReq_data:
      properties:
        type:
          enum:
          - login
          type: string
        attributes:
          $ref: '#/components/schemas/LoginReq_data_attributes'
      required:
      - attributes
      - type
      type: object
    LoginResp_data_attributes:
      properties:
        access_token:
          description: Access Token для авторизации запросов.
          type: string
        refresh_token:
          description: Refresh Token для обновления Access Token.
          type: string
        expires_in:
          description: Время жизни Access Token в секундах.
          type: integer
      required:
      - access_token
      - expires_in
      - refresh_token
      type: object
    LoginResp_data:
      properties:
        type:
          enum:
          - tokens
          type: string
        attributes:
          $ref: '#/components/schemas/LoginResp_data_attributes'
      required:
      - attributes
      - type
      type: object
    ResetPasswordInitiate_data_attributes:
      properties:
        email:
          description: User email (required if username is not provided).
          format: email
          type: string
        username:
          description: User username (required if email is not provided).
          type: string
      type: object
    ResetPasswordInitiate_data:
      properties:
        type:
          enum:
          - reset_password
          type: string
        attributes:
          $ref: '#/components/schemas/ResetPasswordInitiate_data_attributes'
      required:
      - attributes
      - type
      type: object
    ResetPasswordComplete_data_attributes:
      properties:
        first_password:
          description: User password.
          type: string
        second_password:
          description: User password.
          type: string
        email:
          description: User email (required if username is not provided).
          format: email
          type: string
        username:
          description: User username (required if email is not provided).
          type: string
      required:
      - first_password
      - second_password
      type: object
    ResetPasswordComplete_data:
      properties:
        type:
          enum:
          - reset_password
          type: string
        attributes:
          $ref: '#/components/schemas/ResetPasswordComplete_data_attributes'
      required:
      - attributes
      - type
      type: object
    ChangeUsernameReq_data_attributes:
      properties:
        new_username:
          description: New username
          format: username
          type: string
        password:
          description: User password
          type: string
      required:
      - email
      - password
      type: object
    ChangeUsernameReq_data:
      properties:
        type:
          enum:
          - change_username
          type: string
        attributes:
          $ref: '#/components/schemas/ChangeUsernameReq_data_attributes'
      required:
      - attributes
      - type
      type: object
    RefreshReq_data_attributes:
      properties:
        refresh_token:
          description: The refresh token to generate a new access token.
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
          type: string
        device_id:
          description: The device ID of the device that the refresh token was issued
            to. (Not factory ID)
          example: 123e4567-e89b-12d3-a456-426614174000
          format: uuid.UUID
          type: string
        factory_id:
          description: Unique identifier for the user's device.
          type: string
        device_name:
          description: "Human-readable name for the user's device (e.g., 'iPhone 14')."
          type: string
        os_version:
          description: Operating system version of the user's device.
          type: string
      required:
      - device_id
      - device_name
      - factory_id
      - os_version
      - refresh_token
      type: object
    RefreshReq_data:
      properties:
        type:
          enum:
          - refresh
          example: refresh
          type: string
        attributes:
          $ref: '#/components/schemas/RefreshReq_data_attributes'
      required:
      - attributes
      - type
      type: object
    RefreshResp_data_attributes:
      properties:
        access_token:
          description: The new access token.
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
          type: string
        refresh_token:
          description: The new refresh token.
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
          type: string
        expires_in:
          description: Time in seconds until the access token expires.
          example: 3600
          type: integer
      required:
      - access_token
      - expires_in
      - refresh_token
      type: object
    RefreshResp_data:
      properties:
        type:
          enum:
          - refresh
          example: refresh
          type: string
        attributes:
          $ref: '#/components/schemas/RefreshResp_data_attributes'
      required:
      - attributes
      - type
      type: object
