openapi: 3.0.0
info:
  description: This is a sample API.
  title: Example API
  version: 1.0.0
servers:
- url: /
paths:
  /register: {}
  /login: {}
  /change-username: {}
  /refresh: {}
components:
  schemas:
    Registration:
      properties:
        data:
          $ref: '#/components/schemas/Registration_data'
      required:
      - data
      type: object
    LoginReq:
      properties:
        data:
          $ref: '#/components/schemas/LoginReq_data'
      required:
      - data
      type: object
    LoginResp:
      properties:
        data:
          $ref: '#/components/schemas/LoginResp_data'
      required:
      - data
      type: object
    ChangeUsername:
      properties:
        data:
          $ref: '#/components/schemas/ChangeUsername_data'
      required:
      - data
      type: object
    RefreshReq:
      properties:
        data:
          $ref: '#/components/schemas/RefreshReq_data'
      required:
      - data
      type: object
    RefreshResp:
      properties:
        data:
          $ref: '#/components/schemas/RefreshResp_data'
      required:
      - data
      type: object
    RegistrationReq:
      properties:
        data:
          $ref: '#/components/schemas/Registration_data'
      required:
      - data
      type: object
    ChangeUsernameReq:
      properties:
        data:
          $ref: '#/components/schemas/ChangeUsername_data'
      required:
      - data
      type: object
    Registration_data_attributes:
      properties:
        email:
          description: User email
          format: email
          type: string
        password:
          description: User password
          type: string
      required:
      - email
      - password
      type: object
    Registration_data:
      properties:
        id:
          description: Unique identifier username
          type: string
        type:
          enum:
          - registration
          type: string
        attributes:
          $ref: '#/components/schemas/Registration_data_attributes'
      required:
      - attributes
      - id
      - type
      type: object
    LoginReq_data_attributes:
      properties:
        email:
          description: User email
          format: email
          type: string
        username:
          description: User username
          type: string
        password:
          description: User password
          type: string
      required:
      - password
      type: object
    LoginReq_data:
      properties:
        type:
          enum:
          - login
          type: string
        attributes:
          $ref: '#/components/schemas/LoginReq_data_attributes'
      required:
      - attributes
      - type
      type: object
    LoginResp_data_attributes:
      properties:
        access_token:
          description: JWT access token for API access
          type: string
        refresh_token:
          description: JWT refresh token for generating new access tokens
          type: string
        token_type:
          description: "Type of the token, typically 'Bearer'"
          enum:
          - Bearer
          type: string
      required:
      - access_token
      - refresh_token
      - token_type
      type: object
    LoginResp_data:
      properties:
        type:
          enum:
          - token
          type: string
        id:
          description: User ID (UUID)
          type: string
        attributes:
          $ref: '#/components/schemas/LoginResp_data_attributes'
      required:
      - attributes
      - id
      - type
      type: object
    ChangeUsername_data_attributes:
      properties:
        new_username:
          description: New username
          format: username
          type: string
        password:
          description: User password
          type: string
      required:
      - email
      - password
      type: object
    ChangeUsername_data:
      properties:
        type:
          enum:
          - change_username
          type: string
        attributes:
          $ref: '#/components/schemas/ChangeUsername_data_attributes'
      required:
      - attributes
      - type
      type: object
    RefreshReq_data_attributes:
      properties:
        refresh_token:
          description: The refresh token to generate a new access token.
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
          type: string
      required:
      - refresh_token
      type: object
    RefreshReq_data:
      properties:
        type:
          enum:
          - refresh
          example: refresh
          type: string
        attributes:
          $ref: '#/components/schemas/RefreshReq_data_attributes'
      required:
      - attributes
      - type
      type: object
    RefreshResp_data_attributes:
      properties:
        access_token:
          description: The new access token.
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
          type: string
        refresh_token:
          description: The new refresh token.
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
          type: string
        expires_in:
          description: Time in seconds until the access token expires.
          example: 3600
          type: integer
      required:
      - access_token
      - expires_in
      - refresh_token
      type: object
    RefreshResp_data:
      properties:
        type:
          enum:
          - refresh
          example: refresh
          type: string
        attributes:
          $ref: '#/components/schemas/RefreshResp_data_attributes'
      required:
      - attributes
      - type
      type: object
