openapi: 3.0.0
info:
  description: SSO REST API for Cifra app
  title: Cifra SSO REST API
  version: 0.0.1
servers:
- url: /
paths:
  /aprove-operation:
    patch:
      description: Send a request to approve an operation
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/OperationData'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_aprove_operation_patch_200_response'
          description: User successfully activated email
        "400":
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: One of the parameters is invalid. Refer to the response body
            for details.
        "401":
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: You must provide a valid authorization params.
        "403":
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Forbidden
        "409":
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Conflict
        "415":
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Unsupported Media Type
        "429":
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Too many requests
        "500":
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Internal server error
      summary: Approve operation
      tags:
      - Email
components:
  responses:
    invalidParameter:
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
      description: One of the parameters is invalid. Refer to the response body for
        details.
    invalidAuth:
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
      description: You must provide a valid authorization params.
    forbidden:
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
      description: Forbidden
    conflict:
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
      description: Conflict
    unsupportedMediaType:
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
      description: Unsupported Media Type
    tooManyRequests:
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
      description: Too many requests
    internalError:
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
      description: Internal server error
  schemas:
    Login:
      properties:
        data:
          $ref: '#/components/schemas/Login_data'
      required:
      - data
      type: object
    OperationData:
      properties:
        data:
          $ref: '#/components/schemas/OperationData_data'
      required:
      - data
      type: object
    SessionData:
      properties:
        data:
          $ref: '#/components/schemas/SessionData_data'
      required:
      - data
      type: object
    Sessions:
      properties:
        data:
          $ref: '#/components/schemas/Sessions_data'
      required:
      - data
      type: object
    TokenPair:
      properties:
        data:
          $ref: '#/components/schemas/TokenPair_data'
      required:
      - data
      type: object
    UserData:
      properties:
        data:
          $ref: '#/components/schemas/UserData_data'
      required:
      - data
      type: object
    Errors:
      description: Standard JSON:API error
      properties:
        errors:
          description: Non empty array of errors occurred during request processing
          items:
            $ref: '#/components/schemas/Errors_errors_inner'
          type: array
      required:
      - errors
      type: object
    _aprove_operation_patch_200_response:
      example:
        status: 200
      properties:
        status:
          example: 200
          type: number
      type: object
    Login_data_attributes:
      properties:
        email:
          description: User email (required if username is not provided).
          format: email
          type: string
        username:
          description: User username (required if email is not provided).
          type: string
      type: object
    Login_data:
      properties:
        type:
          enum:
          - reset_password
          type: string
        attributes:
          $ref: '#/components/schemas/Login_data_attributes'
      required:
      - attributes
      - type
      type: object
    OperationData_data_attributes:
      properties:
        email:
          description: New email
          type: string
        code:
          description: User code
          type: string
        operation:
          description: Type of operation
          example: reset_password
          type: string
      required:
      - code
      - email
      - operation
      type: object
    OperationData_data:
      properties:
        type:
          enum:
          - approve_operation
          type: string
        attributes:
          $ref: '#/components/schemas/OperationData_data_attributes'
      required:
      - attributes
      - type
      type: object
    SessionData_data_attributes:
      properties:
        email:
          description: User email
          format: email
          type: string
        username:
          description: User username
          type: string
        factory_id:
          description: Unique identifier for the user's device.
          type: string
        device_name:
          description: "Human-readable name for the user's device (e.g., 'iPhone 14')."
          type: string
        os_version:
          description: Operating system version of the user's device.
          type: string
      required:
      - device_name
      - factory_id
      - os_version
      type: object
    SessionData_data:
      properties:
        type:
          enum:
          - login_complete
          type: string
        attributes:
          $ref: '#/components/schemas/SessionData_data_attributes'
      required:
      - attributes
      - type
      type: object
    Sessions_data_attributes_devices_inner:
      properties:
        id:
          description: Уникальный идентификатор устройства
          format: uuid
          type: string
        factory_id:
          description: Серийный номер устройства
          type: string
        device_name:
          description: "Имя устройства, заданное пользователем"
          type: string
        os_version:
          description: Версия операционной системы устройства
          type: string
        last_used:
          description: Дата и время последнего использования устройства
          format: date-time
          type: string
      required:
      - device_name
      - factory_id
      - id
      - last_used
      - os_version
      type: object
    Sessions_data_attributes:
      properties:
        devices:
          items:
            $ref: '#/components/schemas/Sessions_data_attributes_devices_inner'
          type: array
      required:
      - devices
      type: object
    Sessions_data:
      properties:
        type:
          enum:
          - users_sessions
          type: string
        attributes:
          $ref: '#/components/schemas/Sessions_data_attributes'
      required:
      - attributes
      - type
      type: object
    TokenPair_data_attributes:
      properties:
        access_token:
          description: Access Token для авторизации запросов.
          type: string
        refresh_token:
          description: Refresh Token для обновления Access Token.
          type: string
        expires_in:
          description: Время жизни Access Token в секундах.
          type: integer
      required:
      - access_token
      - expires_in
      - refresh_token
      type: object
    TokenPair_data:
      properties:
        type:
          enum:
          - tokens
          type: string
        attributes:
          $ref: '#/components/schemas/TokenPair_data_attributes'
      required:
      - attributes
      - type
      type: object
    UserData_data_attributes:
      properties:
        email:
          description: User email
          format: email
          type: string
        username:
          description: User username
          type: string
        password:
          description: First password
          type: string
      required:
      - password
      type: object
    UserData_data:
      properties:
        type:
          enum:
          - login_initiate
          type: string
        attributes:
          $ref: '#/components/schemas/UserData_data_attributes'
      required:
      - attributes
      - type
      type: object
    Errors_errors_inner:
      properties:
        title:
          description: "Title is a short, human-readable summary of the problem"
          example: Bad Request
          type: string
        detail:
          description: Detail is a human-readable explanation specific to this occurrence
            of the problem
          example: Request body was expected
          type: string
        status:
          description: Status is the HTTP status code applicable to this problem
          enum:
          - 400
          - 401
          - 403
          - 404
          - 409
          - 500
          example: 400
          type: integer
      required:
      - status
      - title
      type: object
