openapi: 3.0.0
info:
  title: Example API
  version: 1.0.0
servers:
- url: /
paths:
  /register: {}
components:
  schemas:
    Errors:
      required:
      - errors
      type: object
      properties:
        errors:
          type: array
          description: Non empty array of errors occurred during request processing
          items:
            $ref: '#/components/schemas/Errors_errors'
      description: Standard JSON:API error
    Registration:
      required:
      - attributes
      type: object
      properties:
        attributes:
          $ref: '#/components/schemas/Registration_attributes'
      description: Registration request
    Errors_errors:
      required:
      - status
      - title
      type: object
      properties:
        title:
          type: string
          description: "Title is a short, human-readable summary of the problem"
          example: Bad Request
        detail:
          type: string
          description: Detail is a human-readable explanation specific to this occurrence
            of the problem
          example: Request body was expected
        status:
          type: integer
          description: Status is the HTTP status code applicable to this problem
          example: 400
          enum:
          - 400
          - 401
          - 403
          - 404
          - 409
          - 500
    Registration_attributes:
      required:
      - email
      - password
      - username
      type: object
      properties:
        email:
          type: string
          description: User email
          format: email
        username:
          type: string
          description: Unique username
        password:
          type: string
          description: User password
  responses:
    internalError:
      description: Internal server error
      content:
        application/vnd.api+json:
          schema:
            $ref: ./spec/components/schemas/Errors.yaml
    invalidAuth:
      description: You must provide a valid authorization params.
      content:
        application/vnd.api+json:
          schema:
            $ref: ./spec/components/schemas/Errors.yaml
    invalidParameter:
      description: One of the parameters is invalid. Refer to the response body for
        details.
      content:
        application/vnd.api+json:
          schema:
            $ref: ./spec/components/schemas/Errors.yaml
    notFound:
      description: Requested resource does not exist.
      content:
        application/vnd.api+json:
          schema:
            $ref: ./spec/components/schemas/Errors.yaml
