openapi: 3.0.0
info:
  title: Example API
  description: An example API with error responses and user registration
  version: 1.0.0

paths:
  /get-user-session:
    get:
      summary: Get user's session
      description: Endpoint to get user's session
      responses:
        '201':
          description: Updated username successfully
          content:
            application/vnd.api+json:
              schema:
                $ref: '../spec/components/schemas/UserSessions.yaml'
        '400':
          $ref: '../spec/components/responses/invalidParameter.yaml'
        '401':
          $ref: '../spec/components/responses/invalidAuth.yaml'
        '403':
          $ref: '../spec/components/responses/forbidden.yaml'
        '409':
          $ref: '../spec/components/responses/conflict.yaml'
        '415':
          $ref: '../spec/components/responses/unsupportedMediaType.yaml'
        '429':
          $ref: '../spec/components/responses/tooManyRequests.yaml'
        '500':
          $ref: '../spec/components/responses/internalError.yaml'