openapi: 3.0.0
info:
  title: Example API
  description: An example API with error responses and user registration
  version: 1.0.0

paths:
  /login-complete:
    post:
      summary: Confirm login
      description: Endpoint to login a new user with email, username, and password
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '../spec/components/schemas/LoginCompleteReq.yaml'
      responses:
        '201':
          description: User successfully login
          content:
            application/vnd.api+json:
              schema:
                $ref: '../spec/components/schemas/LoginCompleteResp.yaml'
        '400':
          $ref: '../spec/components/responses/invalidParameter.yaml'
        '409':
          $ref: '../spec/components/responses/conflict.yaml'
        '415':
          $ref: '../spec/components/responses/unsupportedMediaType.yaml'
        '429':
          $ref: '../spec/components/responses/tooManyRequests.yaml'
        '500':
          $ref: '../spec/components/responses/internalError.yaml'