openapi: 3.0.0
info:
  title: Example API
  description: An example API with error responses and user registration
  version: 1.0.0

paths:
  /login:
    post:
      summary: Login a new user
      description: Endpoint to register a new user with email, username, and password
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '../spec/components/schemas/LoginReq.yaml'
      responses:
        '201':
          description: User successfully login
          content:
            application/vnd.api+json:
              schema:
                $ref: './Registration.yaml'
        '400':
          $ref: '../spec/components/responses/invalidParameter.yaml'
        '401':
          $ref: '../spec/components/responses/invalidAuth.yaml'
        '404':
          $ref: '../spec/components/responses/notFound.yaml'
        '500':
          $ref: '../spec/components/responses/internalError.yaml'

components:
  schemas:
    Errors:
      type: object
      description: 'Standard JSON:API error'
      required:
        - errors
      properties:
        errors:
          type: array
          description: Non-empty array of errors occurred during request processing
          items:
            type: object
            required:
              - title
              - status
            properties:
              title:
                type: string
                description: 'Title is a short, human-readable summary of the problem'
                example: Bad Request
              detail:
                type: string
                description: 'Detail is a human-readable explanation specific to this occurrence of the problem'
                example: "Request body was expected"
              status:
                type: integer
                description: 'Status is the HTTP status code applicable to this problem'
                example: 400
                enum:
                  - 400
                  - 401
                  - 403
                  - 404
                  - 409
                  - 500