openapi: 3.0.0
info:
  title: Example API
  description: An example API with error responses and user registration
  version: 1.0.0

paths:
  /logout:
    post:
      summary: Logout user
      description: Endpoint to logout user
      responses:
        '201':
          description: User successfully logout
        '400':
          $ref: '../spec/components/responses/invalidParameter.yaml'
        '401':
          $ref: '../spec/components/responses/invalidAuth.yaml'
        '403':
          $ref: '../spec/components/responses/forbidden.yaml'
        '409':
          $ref: '../spec/components/responses/conflict.yaml'
        '415':
          $ref: '../spec/components/responses/unsupportedMediaType.yaml'
        '429':
          $ref: '../spec/components/responses/tooManyRequests.yaml'
        '500':
          $ref: '../spec/components/responses/internalError.yaml'