openapi: 3.0.0
info:
  title: Example API
  description: An example API with error responses and user registration
  version: 1.0.0

paths:
  /register:
    post:
      summary: Register a new user
      description: Endpoint to register a new user with email, username, and password
      requestBody:
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/Registration'
      responses:
        '201':
          description: User successfully registered
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Registration'
        '400':
          $ref: '#/components/responses/invalidParameter'
        '401':
          $ref: '#/components/responses/invalidAuth'
        '404':
          $ref: '#/components/responses/notFound'
        '500':
          $ref: '#/components/responses/internalError'

components:
  schemas:
    Errors:
      type: object
      description: 'Standard JSON:API error'
      required:
        - errors
      properties:
        errors:
          type: array
          description: Non-empty array of errors occurred during request processing
          items:
            type: object
            required:
              - title
              - status
            properties:
              title:
                type: string
                description: 'Title is a short, human-readable summary of the problem'
                example: Bad Request
              detail:
                type: string
                description: 'Detail is a human-readable explanation specific to this occurrence of the problem'
                example: "Request body was expected"
              status:
                type: integer
                description: 'Status is the HTTP status code applicable to this problem'
                example: 400
                enum:
                  - 400
                  - 401
                  - 403
                  - 404
                  - 409
                  - 500

    Registration:
      allOf:
        - $ref: '#/components/schemas/RegistrationBase'
        - type: object
          required:
            - attributes
          properties:
            attributes:
              type: object
              required:
                - username
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  description: User email
                  example: "user@example.com"
                username:
                  type: string
                  description: Unique username
                  example: "uniqueuser123"
                password:
                  type: string
                  description: User password
                  example: "password123"

  responses:
    internalError:
      description: Internal server error
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'

    invalidAuth:
      description: You must provide valid authorization parameters.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'

    invalidParameter:
      description: One of the parameters is invalid. Refer to the response body for details.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'

    notFound:
      description: Requested resource does not exist.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
