openapi: 3.0.0
info:
  title: Example API
  description: This is a sample API.
  version: 1.0.0

paths:
  /register:
    $ref: './paths/Registration.yaml'

components:
  schemas:
    Registration:
      $ref: './spec/components/schemas/RegistrationReq.yaml'
    Login:
        $ref: './spec/components/schemas/LoginReq.yaml'
    ChangeUsername:
        $ref: './spec/components/schemas/ChangeUsernameReq.yaml'
