openapi: 3.0.0
info:
  title: Example API
  description: This is a sample API.
  version: 1.0.0

paths:
  /registertion-initiate:
    $ref: './paths/RegistrationInitiate.yaml'
  /registration-complete:
    $ref: './paths/RegistrationComplete.yaml'
  /aprove-operation:
    $ref: './paths/ApproveOperation.yaml'
  /login:
    $ref: './paths/Login.yaml'
  /change-username:
    $ref: './paths/ChangeUsername.yaml'
  /refresh:
    $ref: './paths/Refresh.yaml'
  /reset-password-initiate:
    $ref: './paths/ResetPasswordInitiate.yaml'
  /reset-password-complete:
    $ref: './paths/ResetPasswordComplete.yaml'

components:
  schemas:
    RegistrationInitiate:
      $ref: './spec/components/schemas/RegistrationInitiate.yaml'
    RegistrationComplete:
        $ref: './spec/components/schemas/RegistrationComplete.yaml'
    ApproveOperationReq:
      $ref: './spec/components/schemas/ApproveOperationReq.yaml'
    LoginReq:
        $ref: './spec/components/schemas/LoginReq.yaml'
    LoginResp:
        $ref: './spec/components/schemas/LoginResp.yaml'
    ResetPasswordInitiate:
        $ref: './spec/components/schemas/ResetPasswordInitiate.yaml'
    ResetPasswordComplete:
        $ref: './spec/components/schemas/ResetPasswordComplete.yaml'
    ChangeUsernameReq:
        $ref: './spec/components/schemas/ChangeUsernameReq.yaml'
    RefreshReq:
        $ref: './spec/components/schemas/RefreshReq.yaml'
    RefreshResp:
        $ref: './spec/components/schemas/RefreshResp.yaml'
