openapi: 3.0.0
info:
  title: Example API
  description: This is a sample API.
  version: 1.0.0

paths:
  /register:
    $ref: './paths/RegistrationInitiate.yaml'
  /registration-confirm:
    $ref: './paths/RegistrationComplete.yaml'
  /activate-email:
    $ref: './paths/ApproveOperation.yaml'
  /login:
    $ref: './paths/Login.yaml'
  /change-username:
    $ref: './paths/ChangeUsername.yaml'
  /refresh:
    $ref: './paths/Refresh.yaml'
  /forgot-password:
    $ref: './paths/ForgotPassword.yaml'
  /reset-password:
    $ref: './paths/ResetPassword.yaml'

components:
  schemas:
    RegistrationInitiate:
      $ref: './spec/components/schemas/RegistrationInitiate.yaml'
    ApproveOperationReq:
      $ref: './spec/components/schemas/ApproveOperationReq.yaml'
    RegistrationComplete:
        $ref: './spec/components/schemas/RegistrationComplete.yaml'
    LoginReq:
        $ref: './spec/components/schemas/LoginReq.yaml'
    LoginResp:
        $ref: './spec/components/schemas/LoginResp.yaml'
    ForgotPasswordReq:
        $ref: './spec/components/schemas/ForgotPasswordReq.yaml'
    ResetPasswordReq:
        $ref: './spec/components/schemas/ResetPasswordReq.yaml'
    ChangeUsernameReq:
        $ref: './spec/components/schemas/ChangeUsernameReq.yaml'
    RefreshReq:
        $ref: './spec/components/schemas/RefreshReq.yaml'
    RefreshResp:
        $ref: './spec/components/schemas/RefreshResp.yaml'
