openapi: 3.0.0
info:
  title: Cifra SSO REST API
  description: SSO REST API for Cifra app
  version: 0.0.1

paths:
  /aprove-operation:
    $ref: './paths/ApproveOperation.yaml'
#  /registertion-initiate:
#    $ref: './paths/RegistrationInitiate.yaml'
#  /registration-complete:
#    $ref: './paths/RegistrationComplete.yaml'
#  /login-initiate:
#    $ref: './paths/LoginInitiate.yaml'
#  /login-complete:
#    $ref: './paths/LoginComplete.yaml'
#  /refresh:
#    $ref: './paths/Refresh.yaml'
#  /reset-password-initiate:
#    $ref: './paths/ResetPasswordInitiate.yaml'
#  /reset-password-complete:
#    $ref: './paths/ResetPasswordComplete.yaml'
#  /user/change/username:
#    $ref: './paths/ChangeUsername.yaml'
#  /user/change/sessions:
#    $ref: './paths/GetSession.yaml'
#  /user/change/logout:
#    $ref: './paths/Logout.yaml'
#  /user/change/delete-session:
#    $ref: './paths/DeleteSession.yaml'
#  /user/change/terminate-sessions:
#    $ref: './paths/TerminateSessions.yaml'


components:
  schemas:
    Login:
      $ref: './spec/components/schemas/Login.yaml'
    OperationData:
      $ref: './spec/components/schemas/OperationData.yaml'
    SessionData:
      $ref: './spec/components/schemas/SessionData.yaml'
    Sessions:
      $ref: './spec/components/schemas/Sessions.yaml'
    TokenPair:
      $ref: './spec/components/schemas/TokenPair.yaml'
    UserData:
      $ref: './spec/components/schemas/UserData.yaml'