/*
 * Example API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RegistrationAttributes struct {
	// User email
	Email string `json:"email"`
	// Unique username
	Username string `json:"username"`
	// User password
	Password string `json:"password"`
}
