/*
 * Example API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ErrorsErrors struct {
	// Title is a short, human-readable summary of the problem
	Title string `json:"title"`
	// Detail is a human-readable explanation specific to this occurrence of the problem
	Detail string `json:"detail,omitempty"`
	// Status is the HTTP status code applicable to this problem
	Status int32 `json:"status"`
}
